In [2]:
# Import necessary libraries
import optuna
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load the Pima Indian Diabetes dataset from sklearn
# Note: Scikit-learn's built-in 'load_diabetes' is a regression dataset.
# We will load the actual diabetes dataset from an external source
import pandas as pd

# Load the Pima Indian Diabetes dataset (from UCI repository)
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI',
           'DiabetesPedigreeFunction', 'Age', 'Outcome']

# Load the dataset
df = pd.read_csv(url, names=columns)

df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [3]:
import numpy as np

# Replace zero values with NaN in columns where zero is not a valid value
cols_with_missing_vals = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
df[cols_with_missing_vals] = df[cols_with_missing_vals].replace(0, np.nan)

# Impute the missing values with the mean of the respective column
df.fillna(df.mean(), inplace=True)

# Check if there are any remaining missing values
print(df.isnull().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [4]:
# Split into features (X) and target (y)
X = df.drop('Outcome', axis=1)
y = df['Outcome']

# Split data into training and test sets (70% train, 30% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Optional: Scale the data for better model performance
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Check the shape of the data
print(f'Training set shape: {X_train.shape}')
print(f'Test set shape: {X_test.shape}')

Training set shape: (537, 8)
Test set shape: (231, 8)

In [5]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score  # Return the accuracy score for Optuna to maximize

In [6]:
# Create a study object and optimize the objective function
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2026-06-28 16:03:43,929] A new study created in memory with name: no-name-f2580863-8e15-45d4-aa3a-81b3d488b067
[I 2026-06-28 16:03:44,267] Trial 0 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 141, 'max_depth': 6}. Best is trial 0 with value: 0.7597765363128491.
[I 2026-06-28 16:03:44,726] Trial 1 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 196, 'max_depth': 7}. Best is trial 1 with value: 0.7728119180633147.
[I 2026-06-28 16:03:45,006] Trial 2 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 114, 'max_depth': 12}. Best is trial 2 with value: 0.7746741154562384.
[I 2026-06-28 16:03:45,468] Trial 3 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 197, 'max_depth': 13}. Best is trial 2 with value: 0.7746741154562384.
[I 2026-06-28 16:03:45,605] Trial 4 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 58, 'max_depth': 7}. Best is trial 2 with value: 0.7746741154562384.
[I 2026-06-28 16:03:45,731] Trial 5 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 52, 'max_depth': 9}. Best is trial 2 with value: 0.7746741154562384.
[I 2026-06-28 16:03:46,065] Trial 6 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 144, 'max_depth': 8}. Best is trial 2 with value: 0.7746741154562384.
[I 2026-06-28 16:03:46,415] Trial 7 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 15}. Best is trial 2 with value: 0.7746741154562384.
[I 2026-06-28 16:03:46,642] Trial 8 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 104, 'max_depth': 4}. Best is trial 2 with value: 0.7746741154562384.
[I 2026-06-28 16:03:47,032] Trial 9 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 168, 'max_depth': 15}. Best is trial 2 with value: 0.7746741154562384.
[I 2026-06-28 16:03:47,260] Trial 10 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 95, 'max_depth': 20}. Best is trial 2 with value: 0.7746741154562384.
[I 2026-06-28 16:03:47,732] Trial 11 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 197, 'max_depth': 12}. Best is trial 2 with value: 0.7746741154562384.
[I 2026-06-28 16:03:47,994] Trial 12 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 110, 'max_depth': 12}. Best is trial 2 with value: 0.7746741154562384.
[I 2026-06-28 16:03:48,398] Trial 13 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 172, 'max_depth': 13}. Best is trial 2 with value: 0.7746741154562384.
[I 2026-06-28 16:03:48,600] Trial 14 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 84, 'max_depth': 18}. Best is trial 2 with value: 0.7746741154562384.
[I 2026-06-28 16:03:48,907] Trial 15 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 130, 'max_depth': 10}. Best is trial 2 with value: 0.7746741154562384.
[I 2026-06-28 16:03:49,102] Trial 16 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 80, 'max_depth': 16}. Best is trial 2 with value: 0.7746741154562384.
[I 2026-06-28 16:03:49,395] Trial 17 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 124, 'max_depth': 11}. Best is trial 2 with value: 0.7746741154562384.
[I 2026-06-28 16:03:49,772] Trial 18 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 161, 'max_depth': 14}. Best is trial 2 with value: 0.7746741154562384.
[I 2026-06-28 16:03:50,206] Trial 19 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 185, 'max_depth': 17}. Best is trial 2 with value: 0.7746741154562384.
[I 2026-06-28 16:03:50,373] Trial 20 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 70, 'max_depth': 19}. Best is trial 20 with value: 0.7783985102420857.
[I 2026-06-28 16:03:50,534] Trial 21 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 66, 'max_depth': 20}. Best is trial 20 with value: 0.7783985102420857.
[I 2026-06-28 16:03:50,724] Trial 22 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 78, 'max_depth': 19}. Best is trial 20 with value: 0.7783985102420857.
[I 2026-06-28 16:03:50,973] Trial 23 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 117, 'max_depth': 3}. Best is trial 20 with value: 0.7783985102420857.
[I 2026-06-28 16:03:51,208] Trial 24 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 97, 'max_depth': 17}. Best is trial 20 with value: 0.7783985102420857.
[I 2026-06-28 16:03:51,364] Trial 25 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 63, 'max_depth': 14}. Best is trial 20 with value: 0.7783985102420857.
[I 2026-06-28 16:03:51,680] Trial 26 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 135, 'max_depth': 10}. Best is trial 20 with value: 0.7783985102420857.
[I 2026-06-28 16:03:52,043] Trial 27 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 154, 'max_depth': 13}. Best is trial 20 with value: 0.7783985102420857.
[I 2026-06-28 16:03:52,222] Trial 28 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 74, 'max_depth': 18}. Best is trial 20 with value: 0.7783985102420857.
[I 2026-06-28 16:03:52,402] Trial 29 finished with value: 0.7802607076350094 and parameters: {'n_estimators': 70, 'max_depth': 18}. Best is trial 29 with value: 0.7802607076350094.
[I 2026-06-28 16:03:52,575] Trial 30 finished with value: 0.7802607076350094 and parameters: {'n_estimators': 70, 'max_depth': 18}. Best is trial 29 with value: 0.7802607076350094.
[I 2026-06-28 16:03:52,750] Trial 31 finished with value: 0.7802607076350094 and parameters: {'n_estimators': 71, 'max_depth': 18}. Best is trial 29 with value: 0.7802607076350094.
[I 2026-06-28 16:03:52,968] Trial 32 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 89, 'max_depth': 19}. Best is trial 29 with value: 0.7802607076350094.
[I 2026-06-28 16:03:53,137] Trial 33 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 69, 'max_depth': 17}. Best is trial 29 with value: 0.7802607076350094.
[I 2026-06-28 16:03:53,276] Trial 34 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 55, 'max_depth': 19}. Best is trial 29 with value: 0.7802607076350094.
[I 2026-06-28 16:03:53,404] Trial 35 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 50, 'max_depth': 18}. Best is trial 29 with value: 0.7802607076350094.
[I 2026-06-28 16:03:53,622] Trial 36 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 89, 'max_depth': 16}. Best is trial 29 with value: 0.7802607076350094.
[I 2026-06-28 16:03:53,803] Trial 37 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 71, 'max_depth': 20}. Best is trial 29 with value: 0.7802607076350094.
[I 2026-06-28 16:03:53,956] Trial 38 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 61, 'max_depth': 16}. Best is trial 29 with value: 0.7802607076350094.
[I 2026-06-28 16:03:54,163] Trial 39 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 85, 'max_depth': 18}. Best is trial 29 with value: 0.7802607076350094.
[I 2026-06-28 16:03:54,408] Trial 40 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 19}. Best is trial 29 with value: 0.7802607076350094.
[I 2026-06-28 16:03:54,586] Trial 41 finished with value: 0.7839851024208566 and parameters: {'n_estimators': 73, 'max_depth': 18}. Best is trial 41 with value: 0.7839851024208566.
[I 2026-06-28 16:03:54,768] Trial 42 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 75, 'max_depth': 17}. Best is trial 41 with value: 0.7839851024208566.
[I 2026-06-28 16:03:54,914] Trial 43 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 59, 'max_depth': 20}. Best is trial 41 with value: 0.7839851024208566.
[I 2026-06-28 16:03:55,084] Trial 44 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 68, 'max_depth': 15}. Best is trial 41 with value: 0.7839851024208566.
[I 2026-06-28 16:03:55,308] Trial 45 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 92, 'max_depth': 18}. Best is trial 41 with value: 0.7839851024208566.
[I 2026-06-28 16:03:55,503] Trial 46 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 81, 'max_depth': 19}. Best is trial 41 with value: 0.7839851024208566.
[I 2026-06-28 16:03:55,642] Trial 47 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 50, 'max_depth': 16}. Best is trial 41 with value: 0.7839851024208566.
[I 2026-06-28 16:03:55,904] Trial 48 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 107, 'max_depth': 17}. Best is trial 41 with value: 0.7839851024208566.
[I 2026-06-28 16:03:56,051] Trial 49 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 58, 'max_depth': 15}. Best is trial 41 with value: 0.7839851024208566.

In [7]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7839851024208566
Best hyperparameters: {'n_estimators': 73, 'max_depth': 18}

In [8]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.76

## Samplers in Optuna

In [9]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score  # Return the accuracy score for Optuna to maximize

In [10]:
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.RandomSampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2026-06-28 16:04:09,377] A new study created in memory with name: no-name-1525dc19-c059-4ade-bf6b-15ad6f165b74
[I 2026-06-28 16:04:09,704] Trial 0 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 131, 'max_depth': 5}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-06-28 16:04:10,139] Trial 1 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 181, 'max_depth': 7}. Best is trial 1 with value: 0.7728119180633147.
[I 2026-06-28 16:04:10,530] Trial 2 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 177, 'max_depth': 4}. Best is trial 1 with value: 0.7728119180633147.
[I 2026-06-28 16:04:10,995] Trial 3 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 197, 'max_depth': 11}. Best is trial 1 with value: 0.7728119180633147.
[I 2026-06-28 16:04:11,283] Trial 4 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 118, 'max_depth': 17}. Best is trial 4 with value: 0.7783985102420856.
[I 2026-06-28 16:04:11,655] Trial 5 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 156, 'max_depth': 17}. Best is trial 4 with value: 0.7783985102420856.
[I 2026-06-28 16:04:11,892] Trial 6 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 99, 'max_depth': 18}. Best is trial 4 with value: 0.7783985102420856.
[I 2026-06-28 16:04:12,323] Trial 7 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 181, 'max_depth': 19}. Best is trial 4 with value: 0.7783985102420856.
[I 2026-06-28 16:04:12,608] Trial 8 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 119, 'max_depth': 9}. Best is trial 4 with value: 0.7783985102420856.
[I 2026-06-28 16:04:12,990] Trial 9 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 160, 'max_depth': 17}. Best is trial 4 with value: 0.7783985102420856.
[I 2026-06-28 16:04:13,153] Trial 10 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 66, 'max_depth': 9}. Best is trial 4 with value: 0.7783985102420856.
[I 2026-06-28 16:04:13,286] Trial 11 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 55, 'max_depth': 6}. Best is trial 4 with value: 0.7783985102420856.
[I 2026-06-28 16:04:13,459] Trial 12 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 78, 'max_depth': 3}. Best is trial 4 with value: 0.7783985102420856.
[I 2026-06-28 16:04:13,740] Trial 13 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 113, 'max_depth': 14}. Best is trial 4 with value: 0.7783985102420856.
[I 2026-06-28 16:04:13,989] Trial 14 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 116, 'max_depth': 3}. Best is trial 4 with value: 0.7783985102420856.
[I 2026-06-28 16:04:14,318] Trial 15 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 143, 'max_depth': 7}. Best is trial 4 with value: 0.7783985102420856.
[I 2026-06-28 16:04:14,500] Trial 16 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 75, 'max_depth': 14}. Best is trial 4 with value: 0.7783985102420856.
[I 2026-06-28 16:04:14,689] Trial 17 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 86, 'max_depth': 4}. Best is trial 4 with value: 0.7783985102420856.
[I 2026-06-28 16:04:14,851] Trial 18 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 66, 'max_depth': 8}. Best is trial 4 with value: 0.7783985102420856.
[I 2026-06-28 16:04:15,269] Trial 19 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 176, 'max_depth': 10}. Best is trial 4 with value: 0.7783985102420856.
[I 2026-06-28 16:04:15,597] Trial 20 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 135, 'max_depth': 14}. Best is trial 4 with value: 0.7783985102420856.
[I 2026-06-28 16:04:15,949] Trial 21 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 146, 'max_depth': 7}. Best is trial 4 with value: 0.7783985102420856.
[I 2026-06-28 16:04:16,286] Trial 22 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 130, 'max_depth': 20}. Best is trial 4 with value: 0.7783985102420856.
[I 2026-06-28 16:04:16,593] Trial 23 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 129, 'max_depth': 6}. Best is trial 4 with value: 0.7783985102420856.
[I 2026-06-28 16:04:16,740] Trial 24 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 57, 'max_depth': 11}. Best is trial 4 with value: 0.7783985102420856.
[I 2026-06-28 16:04:17,240] Trial 25 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 197, 'max_depth': 18}. Best is trial 4 with value: 0.7783985102420856.
[I 2026-06-28 16:04:17,398] Trial 26 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 62, 'max_depth': 14}. Best is trial 4 with value: 0.7783985102420856.
[I 2026-06-28 16:04:17,826] Trial 27 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 176, 'max_depth': 14}. Best is trial 4 with value: 0.7783985102420856.
[I 2026-06-28 16:04:18,162] Trial 28 finished with value: 0.7746741154562383 and parameters: {'n_estimators': 141, 'max_depth': 7}. Best is trial 4 with value: 0.7783985102420856.
[I 2026-06-28 16:04:18,398] Trial 29 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 96, 'max_depth': 10}. Best is trial 4 with value: 0.7783985102420856.
[I 2026-06-28 16:04:18,633] Trial 30 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 95, 'max_depth': 19}. Best is trial 4 with value: 0.7783985102420856.
[I 2026-06-28 16:04:18,766] Trial 31 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 53, 'max_depth': 11}. Best is trial 4 with value: 0.7783985102420856.
[I 2026-06-28 16:04:18,968] Trial 32 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 80, 'max_depth': 7}. Best is trial 4 with value: 0.7783985102420856.
[I 2026-06-28 16:04:19,452] Trial 33 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 193, 'max_depth': 18}. Best is trial 4 with value: 0.7783985102420856.
[I 2026-06-28 16:04:19,749] Trial 34 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 124, 'max_depth': 6}. Best is trial 4 with value: 0.7783985102420856.
[I 2026-06-28 16:04:19,938] Trial 35 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 75, 'max_depth': 15}. Best is trial 4 with value: 0.7783985102420856.
[I 2026-06-28 16:04:20,174] Trial 36 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 95, 'max_depth': 18}. Best is trial 4 with value: 0.7783985102420856.
[I 2026-06-28 16:04:20,445] Trial 37 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 111, 'max_depth': 12}. Best is trial 4 with value: 0.7783985102420856.
[I 2026-06-28 16:04:20,887] Trial 38 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 193, 'max_depth': 6}. Best is trial 4 with value: 0.7783985102420856.
[I 2026-06-28 16:04:21,043] Trial 39 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 64, 'max_depth': 8}. Best is trial 4 with value: 0.7783985102420856.
[I 2026-06-28 16:04:21,316] Trial 40 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 111, 'max_depth': 13}. Best is trial 4 with value: 0.7783985102420856.
[I 2026-06-28 16:04:21,481] Trial 41 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 66, 'max_depth': 17}. Best is trial 4 with value: 0.7783985102420856.
[I 2026-06-28 16:04:21,759] Trial 42 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 119, 'max_depth': 7}. Best is trial 42 with value: 0.7802607076350093.
[I 2026-06-28 16:04:22,032] Trial 43 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 113, 'max_depth': 17}. Best is trial 42 with value: 0.7802607076350093.
[I 2026-06-28 16:04:22,181] Trial 44 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 59, 'max_depth': 13}. Best is trial 42 with value: 0.7802607076350093.
[I 2026-06-28 16:04:22,427] Trial 45 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 101, 'max_depth': 12}. Best is trial 42 with value: 0.7802607076350093.
[I 2026-06-28 16:04:22,612] Trial 46 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 69, 'max_depth': 12}. Best is trial 42 with value: 0.7802607076350093.
[I 2026-06-28 16:04:23,064] Trial 47 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 189, 'max_depth': 14}. Best is trial 42 with value: 0.7802607076350093.
[I 2026-06-28 16:04:23,471] Trial 48 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 170, 'max_depth': 10}. Best is trial 42 with value: 0.7802607076350093.
[I 2026-06-28 16:04:23,759] Trial 49 finished with value: 0.7560521415270017 and parameters: {'n_estimators': 133, 'max_depth': 3}. Best is trial 42 with value: 0.7802607076350093.

In [11]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7802607076350093
Best hyperparameters: {'n_estimators': 119, 'max_depth': 7}

In [12]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)


# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.75

In [13]:
search_space = {
    'n_estimators': [50, 100, 150, 200],
    'max_depth': [5, 10, 15, 20]
    
}

In [14]:
# Create a study and optimize it using GridSampler
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.GridSampler(search_space))
study.optimize(objective)

[I 2026-06-28 16:04:30,847] A new study created in memory with name: no-name-88e1dd69-d706-40e2-98e9-566892c04926
[I 2026-06-28 16:04:31,082] Trial 0 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 5}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-06-28 16:04:31,453] Trial 1 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 150, 'max_depth': 10}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-06-28 16:04:31,583] Trial 2 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 50, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-06-28 16:04:31,836] Trial 3 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 100, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-06-28 16:04:32,081] Trial 4 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-06-28 16:04:32,206] Trial 5 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 50, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-06-28 16:04:32,549] Trial 6 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 150, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-06-28 16:04:32,933] Trial 7 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-06-28 16:04:33,299] Trial 8 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-06-28 16:04:33,784] Trial 9 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 200, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-06-28 16:04:34,258] Trial 10 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-06-28 16:04:34,737] Trial 11 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-06-28 16:04:35,194] Trial 12 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 200, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-06-28 16:04:35,315] Trial 13 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 50, 'max_depth': 5}. Best is trial 13 with value: 0.7746741154562384.
[I 2026-06-28 16:04:35,566] Trial 14 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 100, 'max_depth': 10}. Best is trial 13 with value: 0.7746741154562384.
[I 2026-06-28 16:04:35,691] Trial 15 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 50, 'max_depth': 20}. Best is trial 13 with value: 0.7746741154562384.

In [15]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7746741154562384
Best hyperparameters: {'n_estimators': 50, 'max_depth': 5}

In [16]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

## Optuna Visualizations

In [17]:
# For visualizations
from optuna.visualization import plot_optimization_history, plot_parallel_coordinate, plot_slice, plot_contour, plot_param_importances

In [18]:
# 1. Optimization History
plot_optimization_history(study).show()

In [19]:
# 2. Parallel Coordinates Plot
plot_parallel_coordinate(study).show()

In [20]:
# 3. Slice Plot
plot_slice(study).show()

In [21]:
# 4. Contour Plot
plot_contour(study).show()

In [22]:
# 5. Hyperparameter Importance
plot_param_importances(study).show()

## Optimizing Multiple ML Models

In [23]:
# Importing the required libraries
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

In [24]:
# Define the objective function for Optuna
def objective(trial):
    # Choose the algorithm to tune
    classifier_name = trial.suggest_categorical('classifier', ['SVM', 'RandomForest', 'GradientBoosting'])

    if classifier_name == 'SVM':
        # SVM hyperparameters
        c = trial.suggest_float('C', 0.1, 100, log=True)
        kernel = trial.suggest_categorical('kernel', ['linear', 'rbf', 'poly', 'sigmoid'])
        gamma = trial.suggest_categorical('gamma', ['scale', 'auto'])

        model = SVC(C=c, kernel=kernel, gamma=gamma, random_state=42)

    elif classifier_name == 'RandomForest':
        # Random Forest hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)
        bootstrap = trial.suggest_categorical('bootstrap', [True, False])

        model = RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            bootstrap=bootstrap,
            random_state=42
        )

    elif classifier_name == 'GradientBoosting':
        # Gradient Boosting hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3, log=True)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)

        model = GradientBoostingClassifier(
            n_estimators=n_estimators,
            learning_rate=learning_rate,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            random_state=42
        )

    # Perform cross-validation and return the mean accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()
    return score

In [25]:
# Create a study and optimize it using CmaEsSampler
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100)

[I 2026-06-28 16:05:10,731] A new study created in memory with name: no-name-9158f5e4-55e2-4952-aa62-459db86785f4
[I 2026-06-28 16:05:10,749] Trial 0 finished with value: 0.7281191806331471 and parameters: {'classifier': 'SVM', 'C': 1.278120209033799, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 0 with value: 0.7281191806331471.
[I 2026-06-28 16:05:11,376] Trial 1 finished with value: 0.7690875232774674 and parameters: {'classifier': 'RandomForest', 'n_estimators': 269, 'max_depth': 15, 'min_samples_split': 7, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 1 with value: 0.7690875232774674.
[I 2026-06-28 16:05:11,565] Trial 2 finished with value: 0.7821229050279329 and parameters: {'classifier': 'RandomForest', 'n_estimators': 97, 'max_depth': 6, 'min_samples_split': 9, 'min_samples_leaf': 6, 'bootstrap': False}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-06-28 16:05:11,979] Trial 3 finished with value: 0.7541899441340782 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 178, 'learning_rate': 0.16167596213498717, 'max_depth': 4, 'min_samples_split': 8, 'min_samples_leaf': 6}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-06-28 16:05:11,991] Trial 4 finished with value: 0.7281191806331471 and parameters: {'classifier': 'SVM', 'C': 1.2100995911670394, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-06-28 16:05:12,187] Trial 5 finished with value: 0.756052141527002 and parameters: {'classifier': 'RandomForest', 'n_estimators': 81, 'max_depth': 11, 'min_samples_split': 8, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-06-28 16:05:13,184] Trial 6 finished with value: 0.7374301675977654 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 295, 'learning_rate': 0.20424935954226123, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 7}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-06-28 16:05:13,200] Trial 7 finished with value: 0.7653631284916201 and parameters: {'classifier': 'SVM', 'C': 1.2009133519209636, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-06-28 16:05:14,169] Trial 8 finished with value: 0.7635009310986964 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 240, 'learning_rate': 0.018237971719284974, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 7}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-06-28 16:05:14,182] Trial 9 finished with value: 0.6890130353817504 and parameters: {'classifier': 'SVM', 'C': 50.89227767725038, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-06-28 16:05:14,358] Trial 10 finished with value: 0.7541899441340781 and parameters: {'classifier': 'RandomForest', 'n_estimators': 79, 'max_depth': 20, 'min_samples_split': 2, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-06-28 16:05:14,738] Trial 11 finished with value: 0.756052141527002 and parameters: {'classifier': 'RandomForest', 'n_estimators': 168, 'max_depth': 16, 'min_samples_split': 10, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-06-28 16:05:15,121] Trial 12 finished with value: 0.7690875232774674 and parameters: {'classifier': 'RandomForest', 'n_estimators': 188, 'max_depth': 13, 'min_samples_split': 6, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-06-28 16:05:15,400] Trial 13 finished with value: 0.7672253258845437 and parameters: {'classifier': 'RandomForest', 'n_estimators': 121, 'max_depth': 4, 'min_samples_split': 10, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-06-28 16:05:15,933] Trial 14 finished with value: 0.7709497206703911 and parameters: {'classifier': 'RandomForest', 'n_estimators': 282, 'max_depth': 18, 'min_samples_split': 6, 'min_samples_leaf': 9, 'bootstrap': False}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-06-28 16:05:16,392] Trial 15 finished with value: 0.7728119180633147 and parameters: {'classifier': 'RandomForest', 'n_estimators': 240, 'max_depth': 19, 'min_samples_split': 5, 'min_samples_leaf': 10, 'bootstrap': False}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-06-28 16:05:16,498] Trial 16 finished with value: 0.7783985102420856 and parameters: {'classifier': 'RandomForest', 'n_estimators': 50, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 9, 'bootstrap': False}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-06-28 16:05:16,610] Trial 17 finished with value: 0.7746741154562384 and parameters: {'classifier': 'RandomForest', 'n_estimators': 53, 'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-06-28 16:05:16,857] Trial 18 finished with value: 0.7728119180633147 and parameters: {'classifier': 'RandomForest', 'n_estimators': 122, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-06-28 16:05:17,094] Trial 19 finished with value: 0.7672253258845437 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 117, 'learning_rate': 0.011902578497464063, 'max_depth': 3, 'min_samples_split': 9, 'min_samples_leaf': 8}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-06-28 16:05:17,217] Trial 20 finished with value: 0.7672253258845437 and parameters: {'classifier': 'RandomForest', 'n_estimators': 57, 'max_depth': 10, 'min_samples_split': 3, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-06-28 16:05:17,322] Trial 21 finished with value: 0.7765363128491621 and parameters: {'classifier': 'RandomForest', 'n_estimators': 50, 'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-06-28 16:05:17,497] Trial 22 finished with value: 0.7783985102420857 and parameters: {'classifier': 'RandomForest', 'n_estimators': 89, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-06-28 16:05:17,706] Trial 23 finished with value: 0.7709497206703911 and parameters: {'classifier': 'RandomForest', 'n_estimators': 97, 'max_depth': 5, 'min_samples_split': 4, 'min_samples_leaf': 9, 'bootstrap': False}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-06-28 16:05:17,991] Trial 24 finished with value: 0.7728119180633147 and parameters: {'classifier': 'RandomForest', 'n_estimators': 147, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 7, 'bootstrap': False}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-06-28 16:05:18,173] Trial 25 finished with value: 0.7783985102420856 and parameters: {'classifier': 'RandomForest', 'n_estimators': 90, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 6, 'bootstrap': False}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-06-28 16:05:18,385] Trial 26 finished with value: 0.7839851024208566 and parameters: {'classifier': 'RandomForest', 'n_estimators': 105, 'max_depth': 11, 'min_samples_split': 3, 'min_samples_leaf': 9, 'bootstrap': False}. Best is trial 26 with value: 0.7839851024208566.
[I 2026-06-28 16:05:18,675] Trial 27 finished with value: 0.7635009310986964 and parameters: {'classifier': 'RandomForest', 'n_estimators': 144, 'max_depth': 12, 'min_samples_split': 3, 'min_samples_leaf': 6, 'bootstrap': False}. Best is trial 26 with value: 0.7839851024208566.
[I 2026-06-28 16:05:18,688] Trial 28 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10355082665017677, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 28 with value: 0.7877094972067038.
[I 2026-06-28 16:05:18,702] Trial 29 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13777175450640633, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 29 with value: 0.7895716945996275.
[I 2026-06-28 16:05:18,715] Trial 30 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.11102436880236285, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 29 with value: 0.7895716945996275.
[I 2026-06-28 16:05:18,729] Trial 31 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1024089770648598, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 29 with value: 0.7895716945996275.
[I 2026-06-28 16:05:18,742] Trial 32 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1059969221748795, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 29 with value: 0.7895716945996275.
[I 2026-06-28 16:05:18,755] Trial 33 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10290415978969836, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 29 with value: 0.7895716945996275.
[I 2026-06-28 16:05:18,769] Trial 34 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10472955238384629, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 29 with value: 0.7895716945996275.
[I 2026-06-28 16:05:18,782] Trial 35 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2861859860573694, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 29 with value: 0.7895716945996275.
[I 2026-06-28 16:05:18,795] Trial 36 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.32683143892144007, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 29 with value: 0.7895716945996275.
[I 2026-06-28 16:05:18,809] Trial 37 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2861851970786087, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 29 with value: 0.7895716945996275.
[I 2026-06-28 16:05:18,822] Trial 38 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2668928114674452, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 29 with value: 0.7895716945996275.
[I 2026-06-28 16:05:18,835] Trial 39 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.110815043799318, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 29 with value: 0.7895716945996275.
[I 2026-06-28 16:05:18,848] Trial 40 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.25661843911976834, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 29 with value: 0.7895716945996275.
[I 2026-06-28 16:05:18,861] Trial 41 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1039956232213054, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 29 with value: 0.7895716945996275.
[I 2026-06-28 16:05:18,873] Trial 42 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.17933556766985526, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 29 with value: 0.7895716945996275.
[I 2026-06-28 16:05:18,887] Trial 43 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.5670454066173297, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 29 with value: 0.7895716945996275.
[I 2026-06-28 16:05:18,902] Trial 44 finished with value: 0.7728119180633147 and parameters: {'classifier': 'SVM', 'C': 0.1655641792839701, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 29 with value: 0.7895716945996275.
[I 2026-06-28 16:05:18,920] Trial 45 finished with value: 0.7094972067039106 and parameters: {'classifier': 'SVM', 'C': 0.10490780679630261, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 29 with value: 0.7895716945996275.
[I 2026-06-28 16:05:18,935] Trial 46 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.52133719704342, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 29 with value: 0.7895716945996275.
[I 2026-06-28 16:05:20,431] Trial 47 finished with value: 0.7299813780260708 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 214, 'learning_rate': 0.05191828156074048, 'max_depth': 14, 'min_samples_split': 9, 'min_samples_leaf': 1}. Best is trial 29 with value: 0.7895716945996275.
[I 2026-06-28 16:05:20,444] Trial 48 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1835171656471182, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 29 with value: 0.7895716945996275.
[I 2026-06-28 16:05:20,458] Trial 49 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.5318662643682415, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 29 with value: 0.7895716945996275.
[I 2026-06-28 16:05:20,471] Trial 50 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1704658259495534, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 29 with value: 0.7895716945996275.
[I 2026-06-28 16:05:20,483] Trial 51 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1007141813902027, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 29 with value: 0.7895716945996275.
[I 2026-06-28 16:05:20,496] Trial 52 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.18537329730697202, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 29 with value: 0.7895716945996275.
[I 2026-06-28 16:05:20,509] Trial 53 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.15754033610442947, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 29 with value: 0.7895716945996275.
[I 2026-06-28 16:05:22,177] Trial 54 finished with value: 0.7243947858472998 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 209, 'learning_rate': 0.06555623208764211, 'max_depth': 15, 'min_samples_split': 6, 'min_samples_leaf': 2}. Best is trial 29 with value: 0.7895716945996275.
[I 2026-06-28 16:05:22,191] Trial 55 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10085687035578504, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 29 with value: 0.7895716945996275.
[I 2026-06-28 16:05:22,207] Trial 56 finished with value: 0.7746741154562384 and parameters: {'classifier': 'SVM', 'C': 0.16144615712595825, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 29 with value: 0.7895716945996275.
[I 2026-06-28 16:05:22,263] Trial 57 finished with value: 0.6778398510242086 and parameters: {'classifier': 'SVM', 'C': 72.2402774792637, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 29 with value: 0.7895716945996275.
[I 2026-06-28 16:05:22,282] Trial 58 finished with value: 0.7597765363128491 and parameters: {'classifier': 'SVM', 'C': 5.983783311486471, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 29 with value: 0.7895716945996275.
[I 2026-06-28 16:05:23,963] Trial 59 finished with value: 0.7411545623836128 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 259, 'learning_rate': 0.03552848535998084, 'max_depth': 17, 'min_samples_split': 7, 'min_samples_leaf': 4}. Best is trial 29 with value: 0.7895716945996275.
[I 2026-06-28 16:05:23,977] Trial 60 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.41049163934427096, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 29 with value: 0.7895716945996275.
[I 2026-06-28 16:05:23,990] Trial 61 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1385557042342423, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 29 with value: 0.7895716945996275.
[I 2026-06-28 16:05:24,004] Trial 62 finished with value: 0.7150837988826816 and parameters: {'classifier': 'SVM', 'C': 0.1695986943862989, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 29 with value: 0.7895716945996275.
[I 2026-06-28 16:05:24,018] Trial 63 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1508417566434272, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 29 with value: 0.7895716945996275.
[I 2026-06-28 16:05:24,031] Trial 64 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.23218411637814823, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 29 with value: 0.7895716945996275.
[I 2026-06-28 16:05:24,044] Trial 65 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14800203951876584, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 29 with value: 0.7895716945996275.
[I 2026-06-28 16:05:24,059] Trial 66 finished with value: 0.7169459962756052 and parameters: {'classifier': 'SVM', 'C': 0.16063804815242258, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 29 with value: 0.7895716945996275.
[I 2026-06-28 16:05:24,074] Trial 67 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.8115849704962508, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 29 with value: 0.7895716945996275.
[I 2026-06-28 16:05:24,093] Trial 68 finished with value: 0.7765363128491619 and parameters: {'classifier': 'SVM', 'C': 3.090730041217278, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 29 with value: 0.7895716945996275.
[I 2026-06-28 16:05:24,107] Trial 69 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13859698601700013, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 29 with value: 0.7895716945996275.
[I 2026-06-28 16:05:25,370] Trial 70 finished with value: 0.7523277467411544 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 207, 'learning_rate': 0.13738808312525413, 'max_depth': 20, 'min_samples_split': 8, 'min_samples_leaf': 3}. Best is trial 29 with value: 0.7895716945996275.
[I 2026-06-28 16:05:25,384] Trial 71 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13636120531181475, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 29 with value: 0.7895716945996275.
[I 2026-06-28 16:05:25,398] Trial 72 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.145649658806257, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 29 with value: 0.7895716945996275.
[I 2026-06-28 16:05:25,413] Trial 73 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2299684925287363, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 29 with value: 0.7895716945996275.
[I 2026-06-28 16:05:25,426] Trial 74 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13521008648247324, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 29 with value: 0.7895716945996275.
[I 2026-06-28 16:05:25,444] Trial 75 finished with value: 0.756052141527002 and parameters: {'classifier': 'SVM', 'C': 0.40001554804455824, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 29 with value: 0.7895716945996275.
[I 2026-06-28 16:05:25,458] Trial 76 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.22522224550524908, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 29 with value: 0.7895716945996275.
[I 2026-06-28 16:05:25,472] Trial 77 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12984424531136327, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 29 with value: 0.7895716945996275.
[I 2026-06-28 16:05:25,529] Trial 78 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 24.91861552730256, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 29 with value: 0.7895716945996275.
[I 2026-06-28 16:05:25,542] Trial 79 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12946771808282412, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 29 with value: 0.7895716945996275.

In [26]:
# Retrieve the best trial
best_trial = study.best_trial
print("Best trial parameters:", best_trial.params)
print("Best trial accuracy:", best_trial.value)

Best trial parameters: {'classifier': 'SVM', 'C': 0.13777175450640633, 'kernel': 'linear', 'gamma': 'auto'}
Best trial accuracy: 0.7895716945996275

In [27]:
study.trials_dataframe()

,number,value,datetime_start,datetime_complete,duration,params_C,params_bootstrap,params_classifier,params_gamma,params_kernel,params_learning_rate,params_max_depth,params_min_samples_leaf,params_min_samples_split,params_n_estimators,state
0,0,0.728119,2026-06-28 16:05:10.733239,2026-06-28 16:05:10.749367,0 days 00:00:00.016128,1.278120,NaN,SVM,scale,poly,NaN,NaN,NaN,NaN,NaN,COMPLETE
1,1,0.769088,2026-06-28 16:05:10.750360,2026-06-28 16:05:11.375990,0 days 00:00:00.625630,NaN,True,RandomForest,NaN,NaN,NaN,15.0,5.0,7.0,269.0,COMPLETE
2,2,0.782123,2026-06-28 16:05:11.376640,2026-06-28 16:05:11.565717,0 days 00:00:00.189077,NaN,False,RandomForest,NaN,NaN,NaN,6.0,6.0,9.0,97.0,COMPLETE
3,3,0.754190,2026-06-28 16:05:11.566356,2026-06-28 16:05:11.979481,0 days 00:00:00.413125,NaN,NaN,GradientBoosting,NaN,NaN,0.161676,4.0,6.0,8.0,178.0,COMPLETE
4,4,0.728119,2026-06-28 16:05:11.980227,2026-06-28 16:05:11.991622,0 days 00:00:00.011395,1.210100,NaN,SVM,auto,poly,NaN,NaN,NaN,NaN,NaN,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,0.785847,2026-06-28 16:05:26.572449,2026-06-28 16:05:26.585949,0 days 00:00:00.013500,0.264417,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
96,96,0.763501,2026-06-28 16:05:26.586479,2026-06-28 16:05:26.605684,0 days 00:00:00.019205,0.195117,NaN,SVM,auto,rbf,NaN,NaN,NaN,NaN,NaN,COMPLETE
97,97,0.789572,2026-06-28 16:05:26.606496,2026-06-28 16:05:26.620422,0 days 00:00:00.013926,0.113085,NaN,SVM,auto,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
98,98,0.787709,2026-06-28 16:05:26.621729,2026-06-28 16:05:26.635431,0 days 00:00:00.013702,0.167355,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
99,99,0.713222,2026-06-28 16:05:26.636080,2026-06-28 16:05:26.649286,0 days 00:00:00.013206,0.147830,NaN,SVM,auto,poly,NaN,NaN,NaN,NaN,NaN,COMPLETE

In [28]:
study.trials_dataframe()['params_classifier'].value_counts()

params_classifier
SVM                 71
RandomForest        20
GradientBoosting     9
Name: count, dtype: int64

In [29]:
study.trials_dataframe().groupby('params_classifier')['value'].mean()

params_classifier
GradientBoosting    0.745500
RandomForest        0.770764
SVM                 0.776458
Name: value, dtype: float64

In [30]:
# 1. Optimization History
plot_optimization_history(study).show()

In [31]:
# 3. Slice Plot
plot_slice(study).show()

In [32]:
# 5. Hyperparameter Importance
plot_param_importances(study).show()

In [36]:
import optuna
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
import numpy as np

# Load the Iris dataset
X, y = load_iris(return_X_y=True)

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the objective function for XGBoost
def objective(trial):
    # Hyperparameter search space
    param = {
        'verbosity': 0,
        'objective': 'multi:softprob',
        'num_class': 3,
        'eval_metric': 'mlogloss',  # Ensure that the eval_metric is specified here
        'booster': 'gbtree',
        'lambda': trial.suggest_float('lambda', 1e-8, 1.0, log=True),
        'alpha': trial.suggest_float('alpha', 1e-8, 1.0, log=True),
        'eta': trial.suggest_float('eta', 0.01, 0.3),
        'gamma': trial.suggest_float('gamma', 1e-8, 1.0, log=True),
        'max_depth': trial.suggest_int('max_depth', 3, 9),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'subsample': trial.suggest_float('subsample', 0.4, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.4, 1.0),
        'n_estimators': 300,
    }

    # Create DMatrix for XGBoost
    dtrain = xgb.DMatrix(X_train, label=y_train)
    dtest = xgb.DMatrix(X_test, label=y_test)

    # Define a pruning callback based on evaluation metrics
    pruning_callback = optuna.integration.XGBoostPruningCallback(trial, "eval-mlogloss")  # Match the metric name in the evals list

    # Train the model
    bst = xgb.train(
        param,
        dtrain,
        num_boost_round=300,
        evals=[(dtrain, "train"), (dtest, "eval")],  # Ensure the eval datasets and names are specified
        early_stopping_rounds=30,
        callbacks=[pruning_callback]
    )

    # Predict on the test set
    preds = bst.predict(dtest)
    best_preds = [int(np.argmax(line)) for line in preds]

    # Return accuracy as the objective value
    accuracy = accuracy_score(y_test, best_preds)
    return accuracy

# Create a study with pruning
study = optuna.create_study(direction='maximize', pruner=optuna.pruners.SuccessiveHalvingPruner())
study.optimize(objective, n_trials=50)

# Output the best trial
print(f"Best trial: {study.best_trial.params}")
print(f"Best accuracy: {study.best_value}")

[I 2026-06-28 16:06:28,020] A new study created in memory with name: no-name-fe4bdbab-8a35-4dcc-9f65-300dce032463

[0]	train-mlogloss:1.00512	eval-mlogloss:1.00390
[1]	train-mlogloss:0.90822	eval-mlogloss:0.90494
[2]	train-mlogloss:0.86619	eval-mlogloss:0.86507
[3]	train-mlogloss:0.83147	eval-mlogloss:0.82976
[4]	train-mlogloss:0.77274	eval-mlogloss:0.76997
[5]	train-mlogloss:0.74567	eval-mlogloss:0.74260
[6]	train-mlogloss:0.68363	eval-mlogloss:0.67368
[7]	train-mlogloss:0.65368	eval-mlogloss:0.64235
[8]	train-mlogloss:0.61818	eval-mlogloss:0.60438
[9]	train-mlogloss:0.58279	eval-mlogloss:0.56784
[10]	train-mlogloss:0.57415	eval-mlogloss:0.56067
[11]	train-mlogloss:0.54151	eval-mlogloss:0.52385
[12]	train-mlogloss:0.52444	eval-mlogloss:0.50608
[13]	train-mlogloss:0.49763	eval-mlogloss:0.47731
[14]	train-mlogloss:0.48360	eval-mlogloss:0.46035
[15]	train-mlogloss:0.46766	eval-mlogloss:0.44324
[16]	train-mlogloss:0.45116	eval-mlogloss:0.42450
[17]	train-mlogloss:0.44364	eval-mlogloss:0.41524
[18]	train-mlogloss:0.43054	eval-mlogloss:0.40042
[19]	train-mlogloss:0.41933	eval-mlogloss:0.38867
[20]	train-mlogloss:0.40016	eval-mlogloss:0.36827
[21]	train-mlogloss:0.39398	eval-mlogloss:0.36238
[22]	train-mlogloss:0.37947	eval-mlogloss:0.34397
[23]	train-mlogloss:0.36934	eval-mlogloss:0.33262
[24]	train-mlogloss:0.35478	eval-mlogloss:0.31644
[25]	train-mlogloss:0.34741	eval-mlogloss:0.30721
[26]	train-mlogloss:0.33390	eval-mlogloss:0.29276
[27]	train-mlogloss:0.32645	eval-mlogloss:0.28440
[28]	train-mlogloss:0.32572	eval-mlogloss:0.28422
[29]	train-mlogloss:0.32150	eval-mlogloss:0.27838
[30]	train-mlogloss:0.31640	eval-mlogloss:0.27264
[31]	train-mlogloss:0.31480	eval-mlogloss:0.27053
[32]	train-mlogloss:0.30784	eval-mlogloss:0.26083
[33]	train-mlogloss:0.30299	eval-mlogloss:0.25325
[34]	train-mlogloss:0.30251	eval-mlogloss:0.25304
[35]	train-mlogloss:0.29700	eval-mlogloss:0.24609
[36]	train-mlogloss:0.29701	eval-mlogloss:0.24605
[37]	train-mlogloss:0.29674	eval-mlogloss:0.24519
[38]	train-mlogloss:0.29309	eval-mlogloss:0.23958
[39]	train-mlogloss:0.29235	eval-mlogloss:0.23850
[40]	train-mlogloss:0.28841	eval-mlogloss:0.23415
[41]	train-mlogloss:0.28831	eval-mlogloss:0.23421
[42]	train-mlogloss:0.28829	eval-mlogloss:0.23422
[43]	train-mlogloss:0.28792	eval-mlogloss:0.23282
[44]	train-mlogloss:0.28776	eval-mlogloss:0.23235
[45]	train-mlogloss:0.28758	eval-mlogloss:0.23177
[46]	train-mlogloss:0.28755	eval-mlogloss:0.23181
[47]	train-mlogloss:0.28475	eval-mlogloss:0.22751
[48]	train-mlogloss:0.28472	eval-mlogloss:0.22732
[49]	train-mlogloss:0.28478	eval-mlogloss:0.22749
[50]	train-mlogloss:0.28469	eval-mlogloss:0.22766
[51]	train-mlogloss:0.28467	eval-mlogloss:0.22754
[52]	train-mlogloss:0.28163	eval-mlogloss:0.22306
[53]	train-mlogloss:0.28105	eval-mlogloss:0.22247
[54]	train-mlogloss:0.28102	eval-mlogloss:0.22226
[55]	train-mlogloss:0.28102	eval-mlogloss:0.22227
[56]	train-mlogloss:0.28098	eval-mlogloss:0.22202
[57]	train-mlogloss:0.28063	eval-mlogloss:0.22112
[58]	train-mlogloss:0.28003	eval-mlogloss:0.22081
[59]	train-mlogloss:0.27678	eval-mlogloss:0.21579
[60]	train-mlogloss:0.27674	eval-mlogloss:0.21585
[61]	train-mlogloss:0.27609	eval-mlogloss:0.21562
[62]	train-mlogloss:0.27589	eval-mlogloss:0.21545
[63]	train-mlogloss:0.27558	eval-mlogloss:0.21444
[64]	train-mlogloss:0.27556	eval-mlogloss:0.21435
[65]	train-mlogloss:0.27535	eval-mlogloss:0.21335
[66]	train-mlogloss:0.27537	eval-mlogloss:0.21318
[67]	train-mlogloss:0.27537	eval-mlogloss:0.21319
[68]	train-mlogloss:0.27486	eval-mlogloss:0.21289
[69]	train-mlogloss:0.27458	eval-mlogloss:0.21274
[70]	train-mlogloss:0.27426	eval-mlogloss:0.21254
[71]	train-mlogloss:0.27421	eval-mlogloss:0.21268
[72]	train-mlogloss:0.27410	eval-mlogloss:0.21256
[73]	train-mlogloss:0.27404	eval-mlogloss:0.21243
[74]	train-mlogloss:0.27394	eval-mlogloss:0.21242
[75]	train-mlogloss:0.27363	eval-mlogloss:0.21107
[76]	train-mlogloss:0.27364	eval-mlogloss:0.21092
[77]	train-mlogloss:0.27362	eval-mlogloss:0.21057
[78]	train-mlogloss:0.27364	eval-mlogloss:0.21052
[79]	train-mlogloss:0.27331	eval-mlogloss:0.21045
[80]	train-mlogloss:0.27280	eval-mlogloss:0.21024
[81]	train-mlogloss:0.27280	eval-mlogloss:0.21021
[82]	train-mlogloss:0.27242	eval-mlogloss:0.21016
[83]	train-mlogloss:0.27225	eval-mlogloss:0.20930
[84]	train-mlogloss:0.27224	eval-mlogloss:0.20934
[85]	train-mlogloss:0.27212	eval-mlogloss:0.20963
[86]	train-mlogloss:0.27200	eval-mlogloss:0.20921
[87]	train-mlogloss:0.27199	eval-mlogloss:0.20941
[88]	train-mlogloss:0.27185	eval-mlogloss:0.20904
[89]	train-mlogloss:0.27184	eval-mlogloss:0.20904
[90]	train-mlogloss:0.27183	eval-mlogloss:0.20913
[91]	train-mlogloss:0.27193	eval-mlogloss:0.20893
[92]	train-mlogloss:0.27176	eval-mlogloss:0.20794
[93]	train-mlogloss:0.27171	eval-mlogloss:0.20778
[94]	train-mlogloss:0.27161	eval-mlogloss:0.20768
[95]	train-mlogloss:0.27149	eval-mlogloss:0.20762
[96]	train-mlogloss:0.27149	eval-mlogloss:0.20774
[97]	train-mlogloss:0.27149	eval-mlogloss:0.20798
[98]	train-mlogloss:0.27104	eval-mlogloss:0.20777
[99]	train-mlogloss:0.27106	eval-mlogloss:0.20751
[100]	train-mlogloss:0.27102	eval-mlogloss:0.20762
[101]	train-mlogloss:0.27098	eval-mlogloss:0.20771
[102]	train-mlogloss:0.27097	eval-mlogloss:0.20758
[103]	train-mlogloss:0.27074	eval-mlogloss:0.20767
[104]	train-mlogloss:0.27064	eval-mlogloss:0.20749
[105]	train-mlogloss:0.27058	eval-mlogloss:0.20732
[106]	train-mlogloss:0.27057	eval-mlogloss:0.20739
[107]	train-mlogloss:0.27057	eval-mlogloss:0.20734
[108]	train-mlogloss:0.27055	eval-mlogloss:0.20736
[109]	train-mlogloss:0.27052	eval-mlogloss:0.20730
[110]	train-mlogloss:0.27043	eval-mlogloss:0.20680
[111]	train-mlogloss:0.27035	eval-mlogloss:0.20652

d:\CODING\MACHINE LEARNING\.venv\Lib\site-packages\optuna\integration\xgboost.py:14: FutureWarning: `optuna.integration.xgboost` has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0. Use `optuna_integration.xgboost` instead.
  optuna_warn(f"{msg} Use `optuna_integration.xgboost` instead.", FutureWarning)

[112]	train-mlogloss:0.27004	eval-mlogloss:0.20620
[113]	train-mlogloss:0.26990	eval-mlogloss:0.20613
[114]	train-mlogloss:0.26987	eval-mlogloss:0.20621
[115]	train-mlogloss:0.26967	eval-mlogloss:0.20605
[116]	train-mlogloss:0.26965	eval-mlogloss:0.20599
[117]	train-mlogloss:0.26591	eval-mlogloss:0.20125
[118]	train-mlogloss:0.26596	eval-mlogloss:0.20133
[119]	train-mlogloss:0.26567	eval-mlogloss:0.20133
[120]	train-mlogloss:0.26573	eval-mlogloss:0.20147
[121]	train-mlogloss:0.26575	eval-mlogloss:0.20173
[122]	train-mlogloss:0.26573	eval-mlogloss:0.20166
[123]	train-mlogloss:0.26569	eval-mlogloss:0.20126
[124]	train-mlogloss:0.26568	eval-mlogloss:0.20110
[125]	train-mlogloss:0.26563	eval-mlogloss:0.20086
[126]	train-mlogloss:0.26565	eval-mlogloss:0.20092
[127]	train-mlogloss:0.26563	eval-mlogloss:0.20099
[128]	train-mlogloss:0.26563	eval-mlogloss:0.20094
[129]	train-mlogloss:0.26562	eval-mlogloss:0.20100
[130]	train-mlogloss:0.26547	eval-mlogloss:0.20078
[131]	train-mlogloss:0.26547	eval-mlogloss:0.20096
[132]	train-mlogloss:0.26540	eval-mlogloss:0.20069
[133]	train-mlogloss:0.26538	eval-mlogloss:0.20061
[134]	train-mlogloss:0.26539	eval-mlogloss:0.20064
[135]	train-mlogloss:0.26531	eval-mlogloss:0.20017
[136]	train-mlogloss:0.26531	eval-mlogloss:0.20033
[137]	train-mlogloss:0.26531	eval-mlogloss:0.20022
[138]	train-mlogloss:0.26531	eval-mlogloss:0.20018
[139]	train-mlogloss:0.26524	eval-mlogloss:0.20006
[140]	train-mlogloss:0.26526	eval-mlogloss:0.19970
[141]	train-mlogloss:0.26514	eval-mlogloss:0.19956
[142]	train-mlogloss:0.26511	eval-mlogloss:0.19980
[143]	train-mlogloss:0.26497	eval-mlogloss:0.19980
[144]	train-mlogloss:0.26497	eval-mlogloss:0.19980
[145]	train-mlogloss:0.26488	eval-mlogloss:0.19975
[146]	train-mlogloss:0.26475	eval-mlogloss:0.19923
[147]	train-mlogloss:0.26470	eval-mlogloss:0.19904
[148]	train-mlogloss:0.26470	eval-mlogloss:0.19926
[149]	train-mlogloss:0.26453	eval-mlogloss:0.19915
[150]	train-mlogloss:0.26451	eval-mlogloss:0.19945
[151]	train-mlogloss:0.26445	eval-mlogloss:0.19943
[152]	train-mlogloss:0.26414	eval-mlogloss:0.19926
[153]	train-mlogloss:0.26405	eval-mlogloss:0.19834
[154]	train-mlogloss:0.26385	eval-mlogloss:0.19829
[155]	train-mlogloss:0.26386	eval-mlogloss:0.19838
[156]	train-mlogloss:0.26359	eval-mlogloss:0.19844
[157]	train-mlogloss:0.26362	eval-mlogloss:0.19875
[158]	train-mlogloss:0.26363	eval-mlogloss:0.19891
[159]	train-mlogloss:0.26360	eval-mlogloss:0.19876
[160]	train-mlogloss:0.26359	eval-mlogloss:0.19863
[161]	train-mlogloss:0.26358	eval-mlogloss:0.19834
[162]	train-mlogloss:0.26354	eval-mlogloss:0.19803
[163]	train-mlogloss:0.26351	eval-mlogloss:0.19803
[164]	train-mlogloss:0.26353	eval-mlogloss:0.19816
[165]	train-mlogloss:0.26344	eval-mlogloss:0.19754
[166]	train-mlogloss:0.26338	eval-mlogloss:0.19736
[167]	train-mlogloss:0.26306	eval-mlogloss:0.19725
[168]	train-mlogloss:0.26311	eval-mlogloss:0.19743
[169]	train-mlogloss:0.26300	eval-mlogloss:0.19725
[170]	train-mlogloss:0.26302	eval-mlogloss:0.19734
[171]	train-mlogloss:0.26299	eval-mlogloss:0.19723
[172]	train-mlogloss:0.26299	eval-mlogloss:0.19709
[173]	train-mlogloss:0.26288	eval-mlogloss:0.19703
[174]	train-mlogloss:0.26284	eval-mlogloss:0.19702
[175]	train-mlogloss:0.26284	eval-mlogloss:0.19699
[176]	train-mlogloss:0.26274	eval-mlogloss:0.19699
[177]	train-mlogloss:0.26267	eval-mlogloss:0.19684
[178]	train-mlogloss:0.26262	eval-mlogloss:0.19653
[179]	train-mlogloss:0.26248	eval-mlogloss:0.19639
[180]	train-mlogloss:0.26248	eval-mlogloss:0.19626
[181]	train-mlogloss:0.26238	eval-mlogloss:0.19598
[182]	train-mlogloss:0.26248	eval-mlogloss:0.19591
[183]	train-mlogloss:0.26244	eval-mlogloss:0.19614
[184]	train-mlogloss:0.26242	eval-mlogloss:0.19613
[185]	train-mlogloss:0.26243	eval-mlogloss:0.19596
[186]	train-mlogloss:0.26241	eval-mlogloss:0.19615
[187]	train-mlogloss:0.26220	eval-mlogloss:0.19641
[188]	train-mlogloss:0.26220	eval-mlogloss:0.19619
[189]	train-mlogloss:0.26210	eval-mlogloss:0.19523
[190]	train-mlogloss:0.26212	eval-mlogloss:0.19507
[191]	train-mlogloss:0.26214	eval-mlogloss:0.19500
[192]	train-mlogloss:0.26214	eval-mlogloss:0.19502
[193]	train-mlogloss:0.26213	eval-mlogloss:0.19510
[194]	train-mlogloss:0.26209	eval-mlogloss:0.19528
[195]	train-mlogloss:0.26207	eval-mlogloss:0.19518
[196]	train-mlogloss:0.26211	eval-mlogloss:0.19517
[197]	train-mlogloss:0.26204	eval-mlogloss:0.19535
[198]	train-mlogloss:0.26205	eval-mlogloss:0.19535
[199]	train-mlogloss:0.25979	eval-mlogloss:0.19217
[200]	train-mlogloss:0.25978	eval-mlogloss:0.19213
[201]	train-mlogloss:0.25978	eval-mlogloss:0.19204
[202]	train-mlogloss:0.25978	eval-mlogloss:0.19209
[203]	train-mlogloss:0.25978	eval-mlogloss:0.19192
[204]	train-mlogloss:0.25956	eval-mlogloss:0.19183
[205]	train-mlogloss:0.25950	eval-mlogloss:0.19145
[206]	train-mlogloss:0.25951	eval-mlogloss:0.19137
[207]	train-mlogloss:0.25948	eval-mlogloss:0.19129
[208]	train-mlogloss:0.25937	eval-mlogloss:0.19126
[209]	train-mlogloss:0.25935	eval-mlogloss:0.19120
[210]	train-mlogloss:0.25930	eval-mlogloss:0.19124
[211]	train-mlogloss:0.25921	eval-mlogloss:0.19121
[212]	train-mlogloss:0.25905	eval-mlogloss:0.19114
[213]	train-mlogloss:0.25904	eval-mlogloss:0.19131
[214]	train-mlogloss:0.25910	eval-mlogloss:0.19152
[215]	train-mlogloss:0.25907	eval-mlogloss:0.19127
[216]	train-mlogloss:0.25907	eval-mlogloss:0.19127
[217]	train-mlogloss:0.25896	eval-mlogloss:0.19092
[218]	train-mlogloss:0.25895	eval-mlogloss:0.19112
[219]	train-mlogloss:0.25893	eval-mlogloss:0.19110
[220]	train-mlogloss:0.25892	eval-mlogloss:0.19101
[221]	train-mlogloss:0.25892	eval-mlogloss:0.19126
[222]	train-mlogloss:0.25890	eval-mlogloss:0.19129
[223]	train-mlogloss:0.25890	eval-mlogloss:0.19122
[224]	train-mlogloss:0.25878	eval-mlogloss:0.19109
[225]	train-mlogloss:0.25876	eval-mlogloss:0.19110
[226]	train-mlogloss:0.25867	eval-mlogloss:0.19112
[227]	train-mlogloss:0.25858	eval-mlogloss:0.19111
[228]	train-mlogloss:0.25854	eval-mlogloss:0.19113
[229]	train-mlogloss:0.25856	eval-mlogloss:0.19116
[230]	train-mlogloss:0.25781	eval-mlogloss:0.18958
[231]	train-mlogloss:0.25774	eval-mlogloss:0.18957
[232]	train-mlogloss:0.25775	eval-mlogloss:0.18972
[233]	train-mlogloss:0.25777	eval-mlogloss:0.18972
[234]	train-mlogloss:0.25778	eval-mlogloss:0.18988
[235]	train-mlogloss:0.25774	eval-mlogloss:0.18981
[236]	train-mlogloss:0.25778	eval-mlogloss:0.18980
[237]	train-mlogloss:0.25778	eval-mlogloss:0.18973
[238]	train-mlogloss:0.25778	eval-mlogloss:0.18952
[239]	train-mlogloss:0.25779	eval-mlogloss:0.18932
[240]	train-mlogloss:0.25781	eval-mlogloss:0.18913
[241]	train-mlogloss:0.25782	eval-mlogloss:0.18905
[242]	train-mlogloss:0.25781	eval-mlogloss:0.18910
[243]	train-mlogloss:0.25780	eval-mlogloss:0.18907
[244]	train-mlogloss:0.25778	eval-mlogloss:0.18923
[245]	train-mlogloss:0.25769	eval-mlogloss:0.18861
[246]	train-mlogloss:0.25769	eval-mlogloss:0.18872
[247]	train-mlogloss:0.25769	eval-mlogloss:0.18880
[248]	train-mlogloss:0.25769	eval-mlogloss:0.18858
[249]	train-mlogloss:0.25770	eval-mlogloss:0.18847
[250]	train-mlogloss:0.25770	eval-mlogloss:0.18851
[251]	train-mlogloss:0.25770	eval-mlogloss:0.18849
[252]	train-mlogloss:0.25772	eval-mlogloss:0.18834
[253]	train-mlogloss:0.25775	eval-mlogloss:0.18816
[254]	train-mlogloss:0.25775	eval-mlogloss:0.18832
[255]	train-mlogloss:0.25779	eval-mlogloss:0.18847
[256]	train-mlogloss:0.25777	eval-mlogloss:0.18844
[257]	train-mlogloss:0.25777	eval-mlogloss:0.18841
[258]	train-mlogloss:0.25775	eval-mlogloss:0.18852
[259]	train-mlogloss:0.25775	eval-mlogloss:0.18856
[260]	train-mlogloss:0.25774	eval-mlogloss:0.18864
[261]	train-mlogloss:0.25774	eval-mlogloss:0.18866
[262]	train-mlogloss:0.25774	eval-mlogloss:0.18867
[263]	train-mlogloss:0.25769	eval-mlogloss:0.18871
[264]	train-mlogloss:0.25754	eval-mlogloss:0.18882
[265]	train-mlogloss:0.25753	eval-mlogloss:0.18899
[266]	train-mlogloss:0.25753	eval-mlogloss:0.18895
[267]	train-mlogloss:0.25754	eval-mlogloss:0.18891
[268]	train-mlogloss:0.25752	eval-mlogloss:0.18884
[269]	train-mlogloss:0.25734	eval-mlogloss:0.18888
[270]	train-mlogloss:0.25734	eval-mlogloss:0.18876
[271]	train-mlogloss:0.25734	eval-mlogloss:0.18911
[272]	train-mlogloss:0.25733	eval-mlogloss:0.18893
[273]	train-mlogloss:0.25730	eval-mlogloss:0.18901
[274]	train-mlogloss:0.25730	eval-mlogloss:0.18897
[275]	train-mlogloss:0.25730	eval-mlogloss:0.18892
[276]	train-mlogloss:0.25730	eval-mlogloss:0.18901
[277]	train-mlogloss:0.25730	eval-mlogloss:0.18901
[278]	train-mlogloss:0.25730	eval-mlogloss:0.18908
[279]	train-mlogloss:0.25730	eval-mlogloss:0.18924
[280]	train-mlogloss:0.25730	eval-mlogloss:0.18934
[281]	train-mlogloss:0.25728	eval-mlogloss:0.18905
[282]	train-mlogloss:0.25730	eval-mlogloss:0.18893
[283]	train-mlogloss:0.25731	eval-mlogloss:0.18903

[I 2026-06-28 16:06:28,469] Trial 0 finished with value: 1.0 and parameters: {'lambda': 0.06003346775403882, 'alpha': 4.744688065878044e-06, 'eta': 0.08908659228768515, 'gamma': 2.2743632008920925e-05, 'max_depth': 6, 'min_child_weight': 10, 'subsample': 0.7322566045414369, 'colsample_bytree': 0.4361896547662477}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:1.02996	eval-mlogloss:1.03077
[1]	train-mlogloss:0.96409	eval-mlogloss:0.96343
[2]	train-mlogloss:0.90322	eval-mlogloss:0.89757
[3]	train-mlogloss:0.84800	eval-mlogloss:0.83772
[4]	train-mlogloss:0.79787	eval-mlogloss:0.78585
[5]	train-mlogloss:0.75103	eval-mlogloss:0.73365
[6]	train-mlogloss:0.71280	eval-mlogloss:0.69398
[7]	train-mlogloss:0.67338	eval-mlogloss:0.65274
[8]	train-mlogloss:0.63805	eval-mlogloss:0.61658
[9]	train-mlogloss:0.60751	eval-mlogloss:0.58522
[10]	train-mlogloss:0.57803	eval-mlogloss:0.55269
[11]	train-mlogloss:0.55117	eval-mlogloss:0.52225
[12]	train-mlogloss:0.52801	eval-mlogloss:0.49900
[13]	train-mlogloss:0.50293	eval-mlogloss:0.47210
[14]	train-mlogloss:0.48070	eval-mlogloss:0.44872
[15]	train-mlogloss:0.45923	eval-mlogloss:0.42583
[16]	train-mlogloss:0.43858	eval-mlogloss:0.40187
[17]	train-mlogloss:0.41828	eval-mlogloss:0.38020
[18]	train-mlogloss:0.40494	eval-mlogloss:0.36630
[19]	train-mlogloss:0.39268	eval-mlogloss:0.35255
[20]	train-mlogloss:0.37723	eval-mlogloss:0.33427
[21]	train-mlogloss:0.36571	eval-mlogloss:0.32138
[22]	train-mlogloss:0.35496	eval-mlogloss:0.30835
[23]	train-mlogloss:0.34594	eval-mlogloss:0.29823
[24]	train-mlogloss:0.33681	eval-mlogloss:0.28782
[25]	train-mlogloss:0.32839	eval-mlogloss:0.27784
[26]	train-mlogloss:0.31936	eval-mlogloss:0.26756
[27]	train-mlogloss:0.30998	eval-mlogloss:0.25750
[28]	train-mlogloss:0.30621	eval-mlogloss:0.25231
[29]	train-mlogloss:0.30542	eval-mlogloss:0.25126
[30]	train-mlogloss:0.30234	eval-mlogloss:0.24766
[31]	train-mlogloss:0.30194	eval-mlogloss:0.24736
[32]	train-mlogloss:0.29797	eval-mlogloss:0.24203
[33]	train-mlogloss:0.29782	eval-mlogloss:0.24163
[34]	train-mlogloss:0.29757	eval-mlogloss:0.24135
[35]	train-mlogloss:0.29422	eval-mlogloss:0.23673
[36]	train-mlogloss:0.29404	eval-mlogloss:0.23662
[37]	train-mlogloss:0.28732	eval-mlogloss:0.22889
[38]	train-mlogloss:0.28059	eval-mlogloss:0.22117
[39]	train-mlogloss:0.28034	eval-mlogloss:0.22112
[40]	train-mlogloss:0.27741	eval-mlogloss:0.21736
[41]	train-mlogloss:0.27739	eval-mlogloss:0.21739
[42]	train-mlogloss:0.27715	eval-mlogloss:0.21685
[43]	train-mlogloss:0.27404	eval-mlogloss:0.21280
[44]	train-mlogloss:0.27382	eval-mlogloss:0.21274
[45]	train-mlogloss:0.27376	eval-mlogloss:0.21286
[46]	train-mlogloss:0.27367	eval-mlogloss:0.21279
[47]	train-mlogloss:0.27143	eval-mlogloss:0.21031
[48]	train-mlogloss:0.27118	eval-mlogloss:0.20954
[49]	train-mlogloss:0.27073	eval-mlogloss:0.20946
[50]	train-mlogloss:0.26906	eval-mlogloss:0.20713
[51]	train-mlogloss:0.26899	eval-mlogloss:0.20709
[52]	train-mlogloss:0.26625	eval-mlogloss:0.20357
[53]	train-mlogloss:0.26339	eval-mlogloss:0.20041
[54]	train-mlogloss:0.26173	eval-mlogloss:0.19819
[55]	train-mlogloss:0.26170	eval-mlogloss:0.19822
[56]	train-mlogloss:0.26160	eval-mlogloss:0.19816
[57]	train-mlogloss:0.26143	eval-mlogloss:0.19803
[58]	train-mlogloss:0.26117	eval-mlogloss:0.19785
[59]	train-mlogloss:0.25910	eval-mlogloss:0.19506
[60]	train-mlogloss:0.25889	eval-mlogloss:0.19501
[61]	train-mlogloss:0.25857	eval-mlogloss:0.19477
[62]	train-mlogloss:0.25835	eval-mlogloss:0.19453
[63]	train-mlogloss:0.25813	eval-mlogloss:0.19390
[64]	train-mlogloss:0.25795	eval-mlogloss:0.19337
[65]	train-mlogloss:0.25766	eval-mlogloss:0.19327
[66]	train-mlogloss:0.25761	eval-mlogloss:0.19334
[67]	train-mlogloss:0.25761	eval-mlogloss:0.19336
[68]	train-mlogloss:0.25741	eval-mlogloss:0.19335
[69]	train-mlogloss:0.25729	eval-mlogloss:0.19321
[70]	train-mlogloss:0.25704	eval-mlogloss:0.19316
[71]	train-mlogloss:0.25684	eval-mlogloss:0.19322
[72]	train-mlogloss:0.25659	eval-mlogloss:0.19245
[73]	train-mlogloss:0.25660	eval-mlogloss:0.19246
[74]	train-mlogloss:0.25367	eval-mlogloss:0.18956
[75]	train-mlogloss:0.25349	eval-mlogloss:0.18893
[76]	train-mlogloss:0.25329	eval-mlogloss:0.18883
[77]	train-mlogloss:0.25326	eval-mlogloss:0.18858
[78]	train-mlogloss:0.25325	eval-mlogloss:0.18845
[79]	train-mlogloss:0.25127	eval-mlogloss:0.18605
[80]	train-mlogloss:0.25127	eval-mlogloss:0.18607
[81]	train-mlogloss:0.25129	eval-mlogloss:0.18610
[82]	train-mlogloss:0.25106	eval-mlogloss:0.18600
[83]	train-mlogloss:0.25093	eval-mlogloss:0.18568
[84]	train-mlogloss:0.25089	eval-mlogloss:0.18564
[85]	train-mlogloss:0.25079	eval-mlogloss:0.18541
[86]	train-mlogloss:0.25075	eval-mlogloss:0.18529
[87]	train-mlogloss:0.25066	eval-mlogloss:0.18510
[88]	train-mlogloss:0.25027	eval-mlogloss:0.18460
[89]	train-mlogloss:0.25024	eval-mlogloss:0.18452
[90]	train-mlogloss:0.25015	eval-mlogloss:0.18443
[91]	train-mlogloss:0.25016	eval-mlogloss:0.18433
[92]	train-mlogloss:0.24993	eval-mlogloss:0.18346
[93]	train-mlogloss:0.24987	eval-mlogloss:0.18324
[94]	train-mlogloss:0.24966	eval-mlogloss:0.18318
[95]	train-mlogloss:0.24950	eval-mlogloss:0.18272
[96]	train-mlogloss:0.24948	eval-mlogloss:0.18270
[97]	train-mlogloss:0.24922	eval-mlogloss:0.18267
[98]	train-mlogloss:0.24908	eval-mlogloss:0.18269
[99]	train-mlogloss:0.24902	eval-mlogloss:0.18262
[100]	train-mlogloss:0.24893	eval-mlogloss:0.18254
[101]	train-mlogloss:0.24892	eval-mlogloss:0.18253
[102]	train-mlogloss:0.24869	eval-mlogloss:0.18246
[103]	train-mlogloss:0.24871	eval-mlogloss:0.18256
[104]	train-mlogloss:0.24868	eval-mlogloss:0.18246
[105]	train-mlogloss:0.24868	eval-mlogloss:0.18241
[106]	train-mlogloss:0.24855	eval-mlogloss:0.18222
[107]	train-mlogloss:0.24851	eval-mlogloss:0.18224
[108]	train-mlogloss:0.24851	eval-mlogloss:0.18226
[109]	train-mlogloss:0.24842	eval-mlogloss:0.18208
[110]	train-mlogloss:0.24839	eval-mlogloss:0.18203
[111]	train-mlogloss:0.24827	eval-mlogloss:0.18158
[112]	train-mlogloss:0.24800	eval-mlogloss:0.18138
[113]	train-mlogloss:0.24800	eval-mlogloss:0.18136
[114]	train-mlogloss:0.24789	eval-mlogloss:0.18134
[115]	train-mlogloss:0.24776	eval-mlogloss:0.18131
[116]	train-mlogloss:0.24768	eval-mlogloss:0.18141
[117]	train-mlogloss:0.24594	eval-mlogloss:0.17931
[118]	train-mlogloss:0.24600	eval-mlogloss:0.17933
[119]	train-mlogloss:0.24574	eval-mlogloss:0.17927
[120]	train-mlogloss:0.24571	eval-mlogloss:0.17934
[121]	train-mlogloss:0.24572	eval-mlogloss:0.17940
[122]	train-mlogloss:0.24445	eval-mlogloss:0.17764
[123]	train-mlogloss:0.24442	eval-mlogloss:0.17747
[124]	train-mlogloss:0.24440	eval-mlogloss:0.17735
[125]	train-mlogloss:0.24424	eval-mlogloss:0.17710
[126]	train-mlogloss:0.24413	eval-mlogloss:0.17706
[127]	train-mlogloss:0.24410	eval-mlogloss:0.17722
[128]	train-mlogloss:0.24408	eval-mlogloss:0.17708
[129]	train-mlogloss:0.24407	eval-mlogloss:0.17698
[130]	train-mlogloss:0.24159	eval-mlogloss:0.17337
[131]	train-mlogloss:0.24140	eval-mlogloss:0.17262
[132]	train-mlogloss:0.24115	eval-mlogloss:0.17238
[133]	train-mlogloss:0.24113	eval-mlogloss:0.17238
[134]	train-mlogloss:0.24114	eval-mlogloss:0.17235
[135]	train-mlogloss:0.24115	eval-mlogloss:0.17230
[136]	train-mlogloss:0.24115	eval-mlogloss:0.17235
[137]	train-mlogloss:0.24115	eval-mlogloss:0.17235
[138]	train-mlogloss:0.24117	eval-mlogloss:0.17224
[139]	train-mlogloss:0.24111	eval-mlogloss:0.17212
[140]	train-mlogloss:0.24114	eval-mlogloss:0.17201
[141]	train-mlogloss:0.24112	eval-mlogloss:0.17182
[142]	train-mlogloss:0.24108	eval-mlogloss:0.17193
[143]	train-mlogloss:0.24096	eval-mlogloss:0.17192
[144]	train-mlogloss:0.24097	eval-mlogloss:0.17190
[145]	train-mlogloss:0.24082	eval-mlogloss:0.17193
[146]	train-mlogloss:0.24081	eval-mlogloss:0.17199
[147]	train-mlogloss:0.24081	eval-mlogloss:0.17199
[148]	train-mlogloss:0.24081	eval-mlogloss:0.17211
[149]	train-mlogloss:0.24055	eval-mlogloss:0.17176
[150]	train-mlogloss:0.24045	eval-mlogloss:0.17143
[151]	train-mlogloss:0.24045	eval-mlogloss:0.17141
[152]	train-mlogloss:0.24034	eval-mlogloss:0.17133
[153]	train-mlogloss:0.24034	eval-mlogloss:0.17123
[154]	train-mlogloss:0.24021	eval-mlogloss:0.17120
[155]	train-mlogloss:0.24021	eval-mlogloss:0.17115
[156]	train-mlogloss:0.23936	eval-mlogloss:0.17009
[157]	train-mlogloss:0.23937	eval-mlogloss:0.17020
[158]	train-mlogloss:0.23938	eval-mlogloss:0.17028
[159]	train-mlogloss:0.23937	eval-mlogloss:0.17018
[160]	train-mlogloss:0.23924	eval-mlogloss:0.17007
[161]	train-mlogloss:0.23923	eval-mlogloss:0.17000
[162]	train-mlogloss:0.23920	eval-mlogloss:0.17003
[163]	train-mlogloss:0.23920	eval-mlogloss:0.17006
[164]	train-mlogloss:0.23921	eval-mlogloss:0.17011
[165]	train-mlogloss:0.23921	eval-mlogloss:0.17013
[166]	train-mlogloss:0.23922	eval-mlogloss:0.17006
[167]	train-mlogloss:0.23922	eval-mlogloss:0.17012
[168]	train-mlogloss:0.23912	eval-mlogloss:0.17024
[169]	train-mlogloss:0.23907	eval-mlogloss:0.17003
[170]	train-mlogloss:0.23897	eval-mlogloss:0.17007
[171]	train-mlogloss:0.23891	eval-mlogloss:0.16976
[172]	train-mlogloss:0.23885	eval-mlogloss:0.16946
[173]	train-mlogloss:0.23886	eval-mlogloss:0.16946
[174]	train-mlogloss:0.23869	eval-mlogloss:0.16936
[175]	train-mlogloss:0.23869	eval-mlogloss:0.16929
[176]	train-mlogloss:0.23870	eval-mlogloss:0.16948
[177]	train-mlogloss:0.23862	eval-mlogloss:0.16912
[178]	train-mlogloss:0.23860	eval-mlogloss:0.16899
[179]	train-mlogloss:0.23849	eval-mlogloss:0.16896
[180]	train-mlogloss:0.23849	eval-mlogloss:0.16888
[181]	train-mlogloss:0.23851	eval-mlogloss:0.16872
[182]	train-mlogloss:0.23845	eval-mlogloss:0.16848
[183]	train-mlogloss:0.23843	eval-mlogloss:0.16852
[184]	train-mlogloss:0.23842	eval-mlogloss:0.16857
[185]	train-mlogloss:0.23844	eval-mlogloss:0.16849
[186]	train-mlogloss:0.23841	eval-mlogloss:0.16864
[187]	train-mlogloss:0.23840	eval-mlogloss:0.16874
[188]	train-mlogloss:0.23841	eval-mlogloss:0.16867
[189]	train-mlogloss:0.23828	eval-mlogloss:0.16798
[190]	train-mlogloss:0.23830	eval-mlogloss:0.16790
[191]	train-mlogloss:0.23827	eval-mlogloss:0.16788
[192]	train-mlogloss:0.23827	eval-mlogloss:0.16786
[193]	train-mlogloss:0.23827	eval-mlogloss:0.16785
[194]	train-mlogloss:0.23818	eval-mlogloss:0.16781
[195]	train-mlogloss:0.23809	eval-mlogloss:0.16783
[196]	train-mlogloss:0.23809	eval-mlogloss:0.16783
[197]	train-mlogloss:0.23809	eval-mlogloss:0.16784
[198]	train-mlogloss:0.23807	eval-mlogloss:0.16771
[199]	train-mlogloss:0.23805	eval-mlogloss:0.16786
[200]	train-mlogloss:0.23805	eval-mlogloss:0.16784
[201]	train-mlogloss:0.23805	eval-mlogloss:0.16786
[202]	train-mlogloss:0.23799	eval-mlogloss:0.16761
[203]	train-mlogloss:0.23795	eval-mlogloss:0.16775
[204]	train-mlogloss:0.23802	eval-mlogloss:0.16775
[205]	train-mlogloss:0.23794	eval-mlogloss:0.16773
[206]	train-mlogloss:0.23790	eval-mlogloss:0.16778
[207]	train-mlogloss:0.23781	eval-mlogloss:0.16761
[208]	train-mlogloss:0.23776	eval-mlogloss:0.16768
[209]	train-mlogloss:0.23776	eval-mlogloss:0.16765
[210]	train-mlogloss:0.23781	eval-mlogloss:0.16780
[211]	train-mlogloss:0.23769	eval-mlogloss:0.16772
[212]	train-mlogloss:0.23767	eval-mlogloss:0.16779
[213]	train-mlogloss:0.23761	eval-mlogloss:0.16750
[214]	train-mlogloss:0.23762	eval-mlogloss:0.16758
[215]	train-mlogloss:0.23760	eval-mlogloss:0.16747
[216]	train-mlogloss:0.23761	eval-mlogloss:0.16755
[217]	train-mlogloss:0.23757	eval-mlogloss:0.16738
[218]	train-mlogloss:0.23756	eval-mlogloss:0.16739
[219]	train-mlogloss:0.23753	eval-mlogloss:0.16730
[220]	train-mlogloss:0.23752	eval-mlogloss:0.16721
[221]	train-mlogloss:0.23753	eval-mlogloss:0.16725
[222]	train-mlogloss:0.23752	eval-mlogloss:0.16725
[223]	train-mlogloss:0.23754	eval-mlogloss:0.16740
[224]	train-mlogloss:0.23756	eval-mlogloss:0.16745
[225]	train-mlogloss:0.23745	eval-mlogloss:0.16737
[226]	train-mlogloss:0.23747	eval-mlogloss:0.16740
[227]	train-mlogloss:0.23741	eval-mlogloss:0.16732
[228]	train-mlogloss:0.23735	eval-mlogloss:0.16705
[229]	train-mlogloss:0.23736	eval-mlogloss:0.16708
[230]	train-mlogloss:0.23735	eval-mlogloss:0.16693
[231]	train-mlogloss:0.23734	eval-mlogloss:0.16692
[232]	train-mlogloss:0.23727	eval-mlogloss:0.16700
[233]	train-mlogloss:0.23717	eval-mlogloss:0.16662
[234]	train-mlogloss:0.23718	eval-mlogloss:0.16668
[235]	train-mlogloss:0.23704	eval-mlogloss:0.16662
[236]	train-mlogloss:0.23703	eval-mlogloss:0.16652
[237]	train-mlogloss:0.23703	eval-mlogloss:0.16655
[238]	train-mlogloss:0.23695	eval-mlogloss:0.16634
[239]	train-mlogloss:0.23697	eval-mlogloss:0.16625
[240]	train-mlogloss:0.23698	eval-mlogloss:0.16622
[241]	train-mlogloss:0.23699	eval-mlogloss:0.16619
[242]	train-mlogloss:0.23699	eval-mlogloss:0.16620
[243]	train-mlogloss:0.23697	eval-mlogloss:0.16609
[244]	train-mlogloss:0.23696	eval-mlogloss:0.16611
[245]	train-mlogloss:0.23694	eval-mlogloss:0.16617
[246]	train-mlogloss:0.23694	eval-mlogloss:0.16627
[247]	train-mlogloss:0.23693	eval-mlogloss:0.16624
[248]	train-mlogloss:0.23694	eval-mlogloss:0.16612
[249]	train-mlogloss:0.23696	eval-mlogloss:0.16605
[250]	train-mlogloss:0.23695	eval-mlogloss:0.16610
[251]	train-mlogloss:0.23695	eval-mlogloss:0.16609
[252]	train-mlogloss:0.23691	eval-mlogloss:0.16605
[253]	train-mlogloss:0.23693	eval-mlogloss:0.16594
[254]	train-mlogloss:0.23692	eval-mlogloss:0.16599
[255]	train-mlogloss:0.23699	eval-mlogloss:0.16594
[256]	train-mlogloss:0.23691	eval-mlogloss:0.16591
[257]	train-mlogloss:0.23691	eval-mlogloss:0.16593
[258]	train-mlogloss:0.23689	eval-mlogloss:0.16596
[259]	train-mlogloss:0.23689	eval-mlogloss:0.16599
[260]	train-mlogloss:0.23688	eval-mlogloss:0.16603
[261]	train-mlogloss:0.23688	eval-mlogloss:0.16601
[262]	train-mlogloss:0.23688	eval-mlogloss:0.16608
[263]	train-mlogloss:0.23683	eval-mlogloss:0.16610
[264]	train-mlogloss:0.23680	eval-mlogloss:0.16606
[265]	train-mlogloss:0.23679	eval-mlogloss:0.16610
[266]	train-mlogloss:0.23679	eval-mlogloss:0.16609
[267]	train-mlogloss:0.23679	eval-mlogloss:0.16609
[268]	train-mlogloss:0.23680	eval-mlogloss:0.16605
[269]	train-mlogloss:0.23679	eval-mlogloss:0.16611
[270]	train-mlogloss:0.23680	eval-mlogloss:0.16609
[271]	train-mlogloss:0.23678	eval-mlogloss:0.16616
[272]	train-mlogloss:0.23678	eval-mlogloss:0.16614
[273]	train-mlogloss:0.23672	eval-mlogloss:0.16603
[274]	train-mlogloss:0.23672	eval-mlogloss:0.16601
[275]	train-mlogloss:0.23672	eval-mlogloss:0.16603
[276]	train-mlogloss:0.23672	eval-mlogloss:0.16602
[277]	train-mlogloss:0.23672	eval-mlogloss:0.16598
[278]	train-mlogloss:0.23673	eval-mlogloss:0.16595
[279]	train-mlogloss:0.23673	eval-mlogloss:0.16595
[280]	train-mlogloss:0.23672	eval-mlogloss:0.16601
[281]	train-mlogloss:0.23671	eval-mlogloss:0.16608
[282]	train-mlogloss:0.23674	eval-mlogloss:0.16592
[283]	train-mlogloss:0.23673	eval-mlogloss:0.16597
[284]	train-mlogloss:0.23672	eval-mlogloss:0.16601
[285]	train-mlogloss:0.23670	eval-mlogloss:0.16609
[286]	train-mlogloss:0.23670	eval-mlogloss:0.16615

[I 2026-06-28 16:06:28,864] Trial 1 finished with value: 1.0 and parameters: {'lambda': 3.3976077068271447e-06, 'alpha': 0.012294482657896278, 'eta': 0.057539771954266766, 'gamma': 7.315022981632297e-08, 'max_depth': 3, 'min_child_weight': 8, 'subsample': 0.6026810841204954, 'colsample_bytree': 0.9544755882910536}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:0.82421	eval-mlogloss:0.80987
[1]	train-mlogloss:0.64227	eval-mlogloss:0.61972

[I 2026-06-28 16:06:28,875] Trial 2 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.78034	eval-mlogloss:0.75344
[1]	train-mlogloss:0.58498	eval-mlogloss:0.55493

[I 2026-06-28 16:06:28,882] Trial 3 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.08028	eval-mlogloss:1.08182
[1]	train-mlogloss:1.06206	eval-mlogloss:1.06329
[2]	train-mlogloss:1.04386	eval-mlogloss:1.04398
[3]	train-mlogloss:1.02642	eval-mlogloss:1.02521
[4]	train-mlogloss:1.00940	eval-mlogloss:1.00767
[5]	train-mlogloss:0.99216	eval-mlogloss:0.98927
[6]	train-mlogloss:0.97671	eval-mlogloss:0.97230
[7]	train-mlogloss:0.96072	eval-mlogloss:0.95530
[8]	train-mlogloss:0.94510	eval-mlogloss:0.93858
[9]	train-mlogloss:0.93124	eval-mlogloss:0.92508
[10]	train-mlogloss:0.91780	eval-mlogloss:0.91016
[11]	train-mlogloss:0.90352	eval-mlogloss:0.89536
[12]	train-mlogloss:0.88886	eval-mlogloss:0.87982
[13]	train-mlogloss:0.87429	eval-mlogloss:0.86469
[14]	train-mlogloss:0.85995	eval-mlogloss:0.84966
[15]	train-mlogloss:0.84690	eval-mlogloss:0.83599
[16]	train-mlogloss:0.83415	eval-mlogloss:0.82217
[17]	train-mlogloss:0.82123	eval-mlogloss:0.80871
[18]	train-mlogloss:0.80846	eval-mlogloss:0.79562
[19]	train-mlogloss:0.79635	eval-mlogloss:0.78246
[20]	train-mlogloss:0.78434	eval-mlogloss:0.76952
[21]	train-mlogloss:0.77272	eval-mlogloss:0.75704
[22]	train-mlogloss:0.76372	eval-mlogloss:0.74712
[23]	train-mlogloss:0.75294	eval-mlogloss:0.73597
[24]	train-mlogloss:0.74220	eval-mlogloss:0.72452
[25]	train-mlogloss:0.73123	eval-mlogloss:0.71319
[26]	train-mlogloss:0.72001	eval-mlogloss:0.70064
[27]	train-mlogloss:0.70898	eval-mlogloss:0.68897
[28]	train-mlogloss:0.69908	eval-mlogloss:0.67842
[29]	train-mlogloss:0.68929	eval-mlogloss:0.66795
[30]	train-mlogloss:0.67941	eval-mlogloss:0.65706
[31]	train-mlogloss:0.66992	eval-mlogloss:0.64712
[32]	train-mlogloss:0.66068	eval-mlogloss:0.63721
[33]	train-mlogloss:0.65135	eval-mlogloss:0.62675
[34]	train-mlogloss:0.64210	eval-mlogloss:0.61709
[35]	train-mlogloss:0.63328	eval-mlogloss:0.60742
[36]	train-mlogloss:0.62514	eval-mlogloss:0.59906
[37]	train-mlogloss:0.61716	eval-mlogloss:0.59115
[38]	train-mlogloss:0.60856	eval-mlogloss:0.58197
[39]	train-mlogloss:0.60007	eval-mlogloss:0.57287
[40]	train-mlogloss:0.59206	eval-mlogloss:0.56403
[41]	train-mlogloss:0.58389	eval-mlogloss:0.55550
[42]	train-mlogloss:0.57597	eval-mlogloss:0.54679
[43]	train-mlogloss:0.56923	eval-mlogloss:0.54013
[44]	train-mlogloss:0.56169	eval-mlogloss:0.53197
[45]	train-mlogloss:0.55443	eval-mlogloss:0.52388
[46]	train-mlogloss:0.54664	eval-mlogloss:0.51521
[47]	train-mlogloss:0.53944	eval-mlogloss:0.50773
[48]	train-mlogloss:0.53208	eval-mlogloss:0.49963
[49]	train-mlogloss:0.52489	eval-mlogloss:0.49177
[50]	train-mlogloss:0.51797	eval-mlogloss:0.48434
[51]	train-mlogloss:0.51247	eval-mlogloss:0.47840
[52]	train-mlogloss:0.50584	eval-mlogloss:0.47173
[53]	train-mlogloss:0.49933	eval-mlogloss:0.46454
[54]	train-mlogloss:0.49304	eval-mlogloss:0.45769
[55]	train-mlogloss:0.48656	eval-mlogloss:0.45049
[56]	train-mlogloss:0.48103	eval-mlogloss:0.44495
[57]	train-mlogloss:0.47503	eval-mlogloss:0.43849
[58]	train-mlogloss:0.46886	eval-mlogloss:0.43177
[59]	train-mlogloss:0.46365	eval-mlogloss:0.42617
[60]	train-mlogloss:0.45816	eval-mlogloss:0.42009
[61]	train-mlogloss:0.45338	eval-mlogloss:0.41499
[62]	train-mlogloss:0.44766	eval-mlogloss:0.40854
[63]	train-mlogloss:0.44223	eval-mlogloss:0.40233
[64]	train-mlogloss:0.43701	eval-mlogloss:0.39696
[65]	train-mlogloss:0.43238	eval-mlogloss:0.39225
[66]	train-mlogloss:0.42800	eval-mlogloss:0.38724
[67]	train-mlogloss:0.42434	eval-mlogloss:0.38330
[68]	train-mlogloss:0.41926	eval-mlogloss:0.37807
[69]	train-mlogloss:0.41470	eval-mlogloss:0.37313
[70]	train-mlogloss:0.41005	eval-mlogloss:0.36800
[71]	train-mlogloss:0.40598	eval-mlogloss:0.36338
[72]	train-mlogloss:0.40228	eval-mlogloss:0.35980
[73]	train-mlogloss:0.39841	eval-mlogloss:0.35536
[74]	train-mlogloss:0.39489	eval-mlogloss:0.35143
[75]	train-mlogloss:0.39030	eval-mlogloss:0.34648
[76]	train-mlogloss:0.38601	eval-mlogloss:0.34148
[77]	train-mlogloss:0.38211	eval-mlogloss:0.33726
[78]	train-mlogloss:0.37860	eval-mlogloss:0.33369
[79]	train-mlogloss:0.37426	eval-mlogloss:0.32875
[80]	train-mlogloss:0.37068	eval-mlogloss:0.32471
[81]	train-mlogloss:0.36791	eval-mlogloss:0.32177
[82]	train-mlogloss:0.36373	eval-mlogloss:0.31724
[83]	train-mlogloss:0.36045	eval-mlogloss:0.31321
[84]	train-mlogloss:0.35761	eval-mlogloss:0.31029
[85]	train-mlogloss:0.35453	eval-mlogloss:0.30681
[86]	train-mlogloss:0.35128	eval-mlogloss:0.30320
[87]	train-mlogloss:0.34817	eval-mlogloss:0.29979
[88]	train-mlogloss:0.34551	eval-mlogloss:0.29710
[89]	train-mlogloss:0.34212	eval-mlogloss:0.29342
[90]	train-mlogloss:0.33841	eval-mlogloss:0.28933
[91]	train-mlogloss:0.33578	eval-mlogloss:0.28611
[92]	train-mlogloss:0.33279	eval-mlogloss:0.28265
[93]	train-mlogloss:0.32972	eval-mlogloss:0.27919
[94]	train-mlogloss:0.32712	eval-mlogloss:0.27642
[95]	train-mlogloss:0.32392	eval-mlogloss:0.27268
[96]	train-mlogloss:0.32157	eval-mlogloss:0.27006
[97]	train-mlogloss:0.31869	eval-mlogloss:0.26703
[98]	train-mlogloss:0.31660	eval-mlogloss:0.26501
[99]	train-mlogloss:0.31416	eval-mlogloss:0.26233
[100]	train-mlogloss:0.31172	eval-mlogloss:0.25977
[101]	train-mlogloss:0.30938	eval-mlogloss:0.25727
[102]	train-mlogloss:0.30702	eval-mlogloss:0.25477
[103]	train-mlogloss:0.30478	eval-mlogloss:0.25220
[104]	train-mlogloss:0.30218	eval-mlogloss:0.24932
[105]	train-mlogloss:0.29987	eval-mlogloss:0.24685
[106]	train-mlogloss:0.29771	eval-mlogloss:0.24451
[107]	train-mlogloss:0.29659	eval-mlogloss:0.24302
[108]	train-mlogloss:0.29453	eval-mlogloss:0.24057
[109]	train-mlogloss:0.29273	eval-mlogloss:0.23861
[110]	train-mlogloss:0.29201	eval-mlogloss:0.23789
[111]	train-mlogloss:0.29046	eval-mlogloss:0.23614
[112]	train-mlogloss:0.28811	eval-mlogloss:0.23362
[113]	train-mlogloss:0.28595	eval-mlogloss:0.23103
[114]	train-mlogloss:0.28400	eval-mlogloss:0.22881
[115]	train-mlogloss:0.28172	eval-mlogloss:0.22630
[116]	train-mlogloss:0.27985	eval-mlogloss:0.22435
[117]	train-mlogloss:0.27806	eval-mlogloss:0.22232
[118]	train-mlogloss:0.27622	eval-mlogloss:0.22041
[119]	train-mlogloss:0.27509	eval-mlogloss:0.21910
[120]	train-mlogloss:0.27356	eval-mlogloss:0.21750
[121]	train-mlogloss:0.27209	eval-mlogloss:0.21576
[122]	train-mlogloss:0.27032	eval-mlogloss:0.21380
[123]	train-mlogloss:0.26937	eval-mlogloss:0.21289
[124]	train-mlogloss:0.26756	eval-mlogloss:0.21064
[125]	train-mlogloss:0.26575	eval-mlogloss:0.20864
[126]	train-mlogloss:0.26486	eval-mlogloss:0.20750
[127]	train-mlogloss:0.26427	eval-mlogloss:0.20682
[128]	train-mlogloss:0.26327	eval-mlogloss:0.20572
[129]	train-mlogloss:0.26327	eval-mlogloss:0.20571
[130]	train-mlogloss:0.26143	eval-mlogloss:0.20361
[131]	train-mlogloss:0.25993	eval-mlogloss:0.20181
[132]	train-mlogloss:0.25919	eval-mlogloss:0.20084
[133]	train-mlogloss:0.25744	eval-mlogloss:0.19879
[134]	train-mlogloss:0.25656	eval-mlogloss:0.19750
[135]	train-mlogloss:0.25567	eval-mlogloss:0.19664
[136]	train-mlogloss:0.25495	eval-mlogloss:0.19565
[137]	train-mlogloss:0.25350	eval-mlogloss:0.19394
[138]	train-mlogloss:0.25211	eval-mlogloss:0.19244
[139]	train-mlogloss:0.25168	eval-mlogloss:0.19190
[140]	train-mlogloss:0.25026	eval-mlogloss:0.19035
[141]	train-mlogloss:0.24961	eval-mlogloss:0.18958
[142]	train-mlogloss:0.24961	eval-mlogloss:0.18959
[143]	train-mlogloss:0.24946	eval-mlogloss:0.18947
[144]	train-mlogloss:0.24804	eval-mlogloss:0.18794
[145]	train-mlogloss:0.24769	eval-mlogloss:0.18750
[146]	train-mlogloss:0.24670	eval-mlogloss:0.18640
[147]	train-mlogloss:0.24532	eval-mlogloss:0.18496
[148]	train-mlogloss:0.24482	eval-mlogloss:0.18440
[149]	train-mlogloss:0.24395	eval-mlogloss:0.18325
[150]	train-mlogloss:0.24331	eval-mlogloss:0.18243
[151]	train-mlogloss:0.24299	eval-mlogloss:0.18204
[152]	train-mlogloss:0.24241	eval-mlogloss:0.18139
[153]	train-mlogloss:0.24116	eval-mlogloss:0.17985
[154]	train-mlogloss:0.24107	eval-mlogloss:0.17974
[155]	train-mlogloss:0.24058	eval-mlogloss:0.17912
[156]	train-mlogloss:0.24007	eval-mlogloss:0.17846
[157]	train-mlogloss:0.23932	eval-mlogloss:0.17764
[158]	train-mlogloss:0.23876	eval-mlogloss:0.17705
[159]	train-mlogloss:0.23817	eval-mlogloss:0.17622
[160]	train-mlogloss:0.23810	eval-mlogloss:0.17618
[161]	train-mlogloss:0.23801	eval-mlogloss:0.17587
[162]	train-mlogloss:0.23796	eval-mlogloss:0.17570
[163]	train-mlogloss:0.23779	eval-mlogloss:0.17570
[164]	train-mlogloss:0.23706	eval-mlogloss:0.17496
[165]	train-mlogloss:0.23650	eval-mlogloss:0.17412
[166]	train-mlogloss:0.23647	eval-mlogloss:0.17415
[167]	train-mlogloss:0.23600	eval-mlogloss:0.17357
[168]	train-mlogloss:0.23595	eval-mlogloss:0.17365
[169]	train-mlogloss:0.23588	eval-mlogloss:0.17339
[170]	train-mlogloss:0.23563	eval-mlogloss:0.17301
[171]	train-mlogloss:0.23511	eval-mlogloss:0.17238
[172]	train-mlogloss:0.23458	eval-mlogloss:0.17169
[173]	train-mlogloss:0.23400	eval-mlogloss:0.17092
[174]	train-mlogloss:0.23337	eval-mlogloss:0.17024
[175]	train-mlogloss:0.23292	eval-mlogloss:0.16950
[176]	train-mlogloss:0.23284	eval-mlogloss:0.16945
[177]	train-mlogloss:0.23276	eval-mlogloss:0.16934
[178]	train-mlogloss:0.23276	eval-mlogloss:0.16933
[179]	train-mlogloss:0.23267	eval-mlogloss:0.16921
[180]	train-mlogloss:0.23267	eval-mlogloss:0.16919
[181]	train-mlogloss:0.23266	eval-mlogloss:0.16922
[182]	train-mlogloss:0.23206	eval-mlogloss:0.16863
[183]	train-mlogloss:0.23163	eval-mlogloss:0.16808
[184]	train-mlogloss:0.23127	eval-mlogloss:0.16758
[185]	train-mlogloss:0.23127	eval-mlogloss:0.16758
[186]	train-mlogloss:0.23127	eval-mlogloss:0.16760
[187]	train-mlogloss:0.23127	eval-mlogloss:0.16760
[188]	train-mlogloss:0.23085	eval-mlogloss:0.16719
[189]	train-mlogloss:0.23080	eval-mlogloss:0.16698
[190]	train-mlogloss:0.23071	eval-mlogloss:0.16685
[191]	train-mlogloss:0.23041	eval-mlogloss:0.16646
[192]	train-mlogloss:0.23032	eval-mlogloss:0.16632
[193]	train-mlogloss:0.23032	eval-mlogloss:0.16631
[194]	train-mlogloss:0.23026	eval-mlogloss:0.16629
[195]	train-mlogloss:0.23018	eval-mlogloss:0.16617
[196]	train-mlogloss:0.22989	eval-mlogloss:0.16580
[197]	train-mlogloss:0.22985	eval-mlogloss:0.16577
[198]	train-mlogloss:0.22961	eval-mlogloss:0.16544
[199]	train-mlogloss:0.22918	eval-mlogloss:0.16499
[200]	train-mlogloss:0.22890	eval-mlogloss:0.16459
[201]	train-mlogloss:0.22864	eval-mlogloss:0.16422
[202]	train-mlogloss:0.22855	eval-mlogloss:0.16410
[203]	train-mlogloss:0.22850	eval-mlogloss:0.16408
[204]	train-mlogloss:0.22840	eval-mlogloss:0.16406
[205]	train-mlogloss:0.22802	eval-mlogloss:0.16357
[206]	train-mlogloss:0.22802	eval-mlogloss:0.16357
[207]	train-mlogloss:0.22802	eval-mlogloss:0.16355
[208]	train-mlogloss:0.22798	eval-mlogloss:0.16338
[209]	train-mlogloss:0.22752	eval-mlogloss:0.16274
[210]	train-mlogloss:0.22753	eval-mlogloss:0.16276
[211]	train-mlogloss:0.22745	eval-mlogloss:0.16266
[212]	train-mlogloss:0.22730	eval-mlogloss:0.16247
[213]	train-mlogloss:0.22706	eval-mlogloss:0.16215
[214]	train-mlogloss:0.22698	eval-mlogloss:0.16212
[215]	train-mlogloss:0.22678	eval-mlogloss:0.16191
[216]	train-mlogloss:0.22673	eval-mlogloss:0.16186
[217]	train-mlogloss:0.22672	eval-mlogloss:0.16184
[218]	train-mlogloss:0.22630	eval-mlogloss:0.16129
[219]	train-mlogloss:0.22587	eval-mlogloss:0.16066
[220]	train-mlogloss:0.22587	eval-mlogloss:0.16066
[221]	train-mlogloss:0.22547	eval-mlogloss:0.16021
[222]	train-mlogloss:0.22546	eval-mlogloss:0.16021
[223]	train-mlogloss:0.22530	eval-mlogloss:0.16002
[224]	train-mlogloss:0.22531	eval-mlogloss:0.16002
[225]	train-mlogloss:0.22531	eval-mlogloss:0.16001
[226]	train-mlogloss:0.22531	eval-mlogloss:0.16001
[227]	train-mlogloss:0.22526	eval-mlogloss:0.15997
[228]	train-mlogloss:0.22486	eval-mlogloss:0.15939
[229]	train-mlogloss:0.22479	eval-mlogloss:0.15933
[230]	train-mlogloss:0.22420	eval-mlogloss:0.15862
[231]	train-mlogloss:0.22412	eval-mlogloss:0.15857
[232]	train-mlogloss:0.22412	eval-mlogloss:0.15858
[233]	train-mlogloss:0.22409	eval-mlogloss:0.15850
[234]	train-mlogloss:0.22409	eval-mlogloss:0.15852
[235]	train-mlogloss:0.22367	eval-mlogloss:0.15800
[236]	train-mlogloss:0.22361	eval-mlogloss:0.15795
[237]	train-mlogloss:0.22360	eval-mlogloss:0.15790
[238]	train-mlogloss:0.22360	eval-mlogloss:0.15788
[239]	train-mlogloss:0.22360	eval-mlogloss:0.15788
[240]	train-mlogloss:0.22361	eval-mlogloss:0.15787
[241]	train-mlogloss:0.22313	eval-mlogloss:0.15726
[242]	train-mlogloss:0.22313	eval-mlogloss:0.15726
[243]	train-mlogloss:0.22279	eval-mlogloss:0.15682
[244]	train-mlogloss:0.22279	eval-mlogloss:0.15682
[245]	train-mlogloss:0.22274	eval-mlogloss:0.15666
[246]	train-mlogloss:0.22275	eval-mlogloss:0.15668
[247]	train-mlogloss:0.22271	eval-mlogloss:0.15670
[248]	train-mlogloss:0.22271	eval-mlogloss:0.15667
[249]	train-mlogloss:0.22271	eval-mlogloss:0.15666
[250]	train-mlogloss:0.22271	eval-mlogloss:0.15667
[251]	train-mlogloss:0.22270	eval-mlogloss:0.15666
[252]	train-mlogloss:0.22271	eval-mlogloss:0.15667
[253]	train-mlogloss:0.22271	eval-mlogloss:0.15665
[254]	train-mlogloss:0.22274	eval-mlogloss:0.15671
[255]	train-mlogloss:0.22274	eval-mlogloss:0.15670
[256]	train-mlogloss:0.22266	eval-mlogloss:0.15658
[257]	train-mlogloss:0.22266	eval-mlogloss:0.15658
[258]	train-mlogloss:0.22261	eval-mlogloss:0.15655
[259]	train-mlogloss:0.22261	eval-mlogloss:0.15655
[260]	train-mlogloss:0.22261	eval-mlogloss:0.15656
[261]	train-mlogloss:0.22255	eval-mlogloss:0.15653
[262]	train-mlogloss:0.22255	eval-mlogloss:0.15654
[263]	train-mlogloss:0.22254	eval-mlogloss:0.15658
[264]	train-mlogloss:0.22246	eval-mlogloss:0.15664
[265]	train-mlogloss:0.22246	eval-mlogloss:0.15664
[266]	train-mlogloss:0.22218	eval-mlogloss:0.15624
[267]	train-mlogloss:0.22218	eval-mlogloss:0.15622
[268]	train-mlogloss:0.22218	eval-mlogloss:0.15622
[269]	train-mlogloss:0.22212	eval-mlogloss:0.15614
[270]	train-mlogloss:0.22164	eval-mlogloss:0.15547
[271]	train-mlogloss:0.22163	eval-mlogloss:0.15548
[272]	train-mlogloss:0.22157	eval-mlogloss:0.15526
[273]	train-mlogloss:0.22149	eval-mlogloss:0.15518
[274]	train-mlogloss:0.22149	eval-mlogloss:0.15518
[275]	train-mlogloss:0.22047	eval-mlogloss:0.15423
[276]	train-mlogloss:0.22048	eval-mlogloss:0.15423
[277]	train-mlogloss:0.22047	eval-mlogloss:0.15421
[278]	train-mlogloss:0.22048	eval-mlogloss:0.15419
[279]	train-mlogloss:0.22047	eval-mlogloss:0.15418
[280]	train-mlogloss:0.22047	eval-mlogloss:0.15419
[281]	train-mlogloss:0.22047	eval-mlogloss:0.15419
[282]	train-mlogloss:0.22047	eval-mlogloss:0.15418
[283]	train-mlogloss:0.22047	eval-mlogloss:0.15418
[284]	train-mlogloss:0.22015	eval-mlogloss:0.15387
[285]	train-mlogloss:0.22009	eval-mlogloss:0.15385
[286]	train-mlogloss:0.22009	eval-mlogloss:0.15386
[287]	train-mlogloss:0.22002	eval-mlogloss:0.15381
[288]	train-mlogloss:0.22002	eval-mlogloss:0.15381
[289]	train-mlogloss:0.22002	eval-mlogloss:0.15380
[290]	train-mlogloss:0.22002	eval-mlogloss:0.15379
[291]	train-mlogloss:0.21957	eval-mlogloss:0.15302
[292]	train-mlogloss:0.21911	eval-mlogloss:0.15245
[293]	train-mlogloss:0.21912	eval-mlogloss:0.15245
[294]	train-mlogloss:0.21912	eval-mlogloss:0.15245
[295]	train-mlogloss:0.21911	eval-mlogloss:0.15245
[296]	train-mlogloss:0.21907	eval-mlogloss:0.15242
[297]	train-mlogloss:0.21908	eval-mlogloss:0.15242
[298]	train-mlogloss:0.21907	eval-mlogloss:0.15242
[299]	train-mlogloss:0.21907	eval-mlogloss:0.15244

[I 2026-06-28 16:06:29,303] Trial 4 finished with value: 1.0 and parameters: {'lambda': 0.022370576916379056, 'alpha': 3.097125144011398e-05, 'eta': 0.014704147982207344, 'gamma': 0.3346965978798393, 'max_depth': 6, 'min_child_weight': 6, 'subsample': 0.5244395325228481, 'colsample_bytree': 0.9531036798640867}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:0.96298	eval-mlogloss:0.95499
[1]	train-mlogloss:0.85229	eval-mlogloss:0.84241

[I 2026-06-28 16:06:29,309] Trial 5 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.96474	eval-mlogloss:0.96205
[1]	train-mlogloss:0.84560	eval-mlogloss:0.83882

[I 2026-06-28 16:06:29,315] Trial 6 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.87729	eval-mlogloss:0.87874
[1]	train-mlogloss:0.71346	eval-mlogloss:0.70753

[I 2026-06-28 16:06:29,322] Trial 7 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.06419	eval-mlogloss:1.06375
[1]	train-mlogloss:1.03173	eval-mlogloss:1.03070
[2]	train-mlogloss:1.00014	eval-mlogloss:0.99663
[3]	train-mlogloss:0.97086	eval-mlogloss:0.96590
[4]	train-mlogloss:0.94170	eval-mlogloss:0.93536
[5]	train-mlogloss:0.91390	eval-mlogloss:0.90680
[6]	train-mlogloss:0.88841	eval-mlogloss:0.87841
[7]	train-mlogloss:0.86354	eval-mlogloss:0.85205

[I 2026-06-28 16:06:29,340] Trial 8 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.01780	eval-mlogloss:1.01774
[1]	train-mlogloss:0.93356	eval-mlogloss:0.93172

[I 2026-06-28 16:06:29,347] Trial 9 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.91069	eval-mlogloss:0.92372
[1]	train-mlogloss:0.74731	eval-mlogloss:0.75752

[I 2026-06-28 16:06:29,364] Trial 10 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.01427	eval-mlogloss:1.01208
[1]	train-mlogloss:0.93663	eval-mlogloss:0.93301

[I 2026-06-28 16:06:29,382] Trial 11 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.06148	eval-mlogloss:1.06427
[1]	train-mlogloss:1.00643	eval-mlogloss:1.00798
[2]	train-mlogloss:0.97065	eval-mlogloss:0.97032
[3]	train-mlogloss:0.94404	eval-mlogloss:0.94184
[4]	train-mlogloss:0.90155	eval-mlogloss:0.89340
[5]	train-mlogloss:0.87800	eval-mlogloss:0.86974
[6]	train-mlogloss:0.86070	eval-mlogloss:0.85176
[7]	train-mlogloss:0.82899	eval-mlogloss:0.81640

[I 2026-06-28 16:06:29,406] Trial 12 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.00592	eval-mlogloss:1.00214
[1]	train-mlogloss:0.92562	eval-mlogloss:0.92031

[I 2026-06-28 16:06:29,421] Trial 13 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.91655	eval-mlogloss:0.90912
[1]	train-mlogloss:0.77406	eval-mlogloss:0.76045

[I 2026-06-28 16:06:29,438] Trial 14 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.05344	eval-mlogloss:1.05563
[1]	train-mlogloss:1.00963	eval-mlogloss:1.01093

[I 2026-06-28 16:06:29,453] Trial 15 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.02165	eval-mlogloss:1.01960
[1]	train-mlogloss:0.95330	eval-mlogloss:0.94989

[I 2026-06-28 16:06:29,469] Trial 16 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.96360	eval-mlogloss:0.96124
[1]	train-mlogloss:0.83397	eval-mlogloss:0.82890

[I 2026-06-28 16:06:29,485] Trial 17 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.97787	eval-mlogloss:0.97291
[1]	train-mlogloss:0.87541	eval-mlogloss:0.86790

[I 2026-06-28 16:06:29,501] Trial 18 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.86314	eval-mlogloss:0.85701
[1]	train-mlogloss:0.73328	eval-mlogloss:0.71321

[I 2026-06-28 16:06:29,519] Trial 19 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.04258	eval-mlogloss:1.04469
[1]	train-mlogloss:0.98897	eval-mlogloss:0.98996
[2]	train-mlogloss:0.93857	eval-mlogloss:0.93538
[3]	train-mlogloss:0.89347	eval-mlogloss:0.88771
[4]	train-mlogloss:0.85045	eval-mlogloss:0.84321
[5]	train-mlogloss:0.80979	eval-mlogloss:0.79780
[6]	train-mlogloss:0.78093	eval-mlogloss:0.76827
[7]	train-mlogloss:0.75731	eval-mlogloss:0.74471

[I 2026-06-28 16:06:29,546] Trial 20 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.08190	eval-mlogloss:1.08349
[1]	train-mlogloss:1.06527	eval-mlogloss:1.06658
[2]	train-mlogloss:1.04863	eval-mlogloss:1.04892
[3]	train-mlogloss:1.03264	eval-mlogloss:1.03172
[4]	train-mlogloss:1.01699	eval-mlogloss:1.01559
[5]	train-mlogloss:1.00145	eval-mlogloss:0.99840
[6]	train-mlogloss:0.98781	eval-mlogloss:0.98372
[7]	train-mlogloss:0.97297	eval-mlogloss:0.96786
[8]	train-mlogloss:0.95839	eval-mlogloss:0.95250
[9]	train-mlogloss:0.94551	eval-mlogloss:0.93995
[10]	train-mlogloss:0.93302	eval-mlogloss:0.92613
[11]	train-mlogloss:0.91967	eval-mlogloss:0.91231
[12]	train-mlogloss:0.90596	eval-mlogloss:0.89779
[13]	train-mlogloss:0.89229	eval-mlogloss:0.88373
[14]	train-mlogloss:0.87886	eval-mlogloss:0.86966
[15]	train-mlogloss:0.86660	eval-mlogloss:0.85682
[16]	train-mlogloss:0.85453	eval-mlogloss:0.84347
[17]	train-mlogloss:0.84234	eval-mlogloss:0.83078
[18]	train-mlogloss:0.83028	eval-mlogloss:0.81842
[19]	train-mlogloss:0.81876	eval-mlogloss:0.80597
[20]	train-mlogloss:0.80740	eval-mlogloss:0.79373
[21]	train-mlogloss:0.79639	eval-mlogloss:0.78191
[22]	train-mlogloss:0.78776	eval-mlogloss:0.77253
[23]	train-mlogloss:0.77742	eval-mlogloss:0.76184
[24]	train-mlogloss:0.76720	eval-mlogloss:0.75095
[25]	train-mlogloss:0.75674	eval-mlogloss:0.74016
[26]	train-mlogloss:0.74604	eval-mlogloss:0.72822
[27]	train-mlogloss:0.73550	eval-mlogloss:0.71706
[28]	train-mlogloss:0.72602	eval-mlogloss:0.70706
[29]	train-mlogloss:0.71667	eval-mlogloss:0.69710
[30]	train-mlogloss:0.70718	eval-mlogloss:0.68672
[31]	train-mlogloss:0.69800	eval-mlogloss:0.67707
[32]	train-mlogloss:0.68911	eval-mlogloss:0.66753
[33]	train-mlogloss:0.68007	eval-mlogloss:0.65746
[34]	train-mlogloss:0.67105	eval-mlogloss:0.64807
[35]	train-mlogloss:0.66252	eval-mlogloss:0.63873
[36]	train-mlogloss:0.65464	eval-mlogloss:0.63065
[37]	train-mlogloss:0.64689	eval-mlogloss:0.62296
[38]	train-mlogloss:0.63856	eval-mlogloss:0.61415
[39]	train-mlogloss:0.63033	eval-mlogloss:0.60532
[40]	train-mlogloss:0.62246	eval-mlogloss:0.59671
[41]	train-mlogloss:0.61451	eval-mlogloss:0.58842
[42]	train-mlogloss:0.60667	eval-mlogloss:0.58001
[43]	train-mlogloss:0.60001	eval-mlogloss:0.57344
[44]	train-mlogloss:0.59269	eval-mlogloss:0.56602
[45]	train-mlogloss:0.58557	eval-mlogloss:0.55810
[46]	train-mlogloss:0.57794	eval-mlogloss:0.54963
[47]	train-mlogloss:0.57085	eval-mlogloss:0.54226
[48]	train-mlogloss:0.56356	eval-mlogloss:0.53445
[49]	train-mlogloss:0.55649	eval-mlogloss:0.52673
[50]	train-mlogloss:0.54967	eval-mlogloss:0.51940
[51]	train-mlogloss:0.54425	eval-mlogloss:0.51355
[52]	train-mlogloss:0.53764	eval-mlogloss:0.50674
[53]	train-mlogloss:0.53106	eval-mlogloss:0.49956
[54]	train-mlogloss:0.52471	eval-mlogloss:0.49273
[55]	train-mlogloss:0.51830	eval-mlogloss:0.48561
[56]	train-mlogloss:0.51221	eval-mlogloss:0.47914
[57]	train-mlogloss:0.50627	eval-mlogloss:0.47275
[58]	train-mlogloss:0.50015	eval-mlogloss:0.46609
[59]	train-mlogloss:0.49469	eval-mlogloss:0.45994
[60]	train-mlogloss:0.48895	eval-mlogloss:0.45376
[61]	train-mlogloss:0.48410	eval-mlogloss:0.44854
[62]	train-mlogloss:0.47835	eval-mlogloss:0.44213
[63]	train-mlogloss:0.47293	eval-mlogloss:0.43593
[64]	train-mlogloss:0.46768	eval-mlogloss:0.43054
[65]	train-mlogloss:0.46308	eval-mlogloss:0.42583
[66]	train-mlogloss:0.45858	eval-mlogloss:0.42073
[67]	train-mlogloss:0.45487	eval-mlogloss:0.41673
[68]	train-mlogloss:0.44974	eval-mlogloss:0.41146
[69]	train-mlogloss:0.44516	eval-mlogloss:0.40651
[70]	train-mlogloss:0.44043	eval-mlogloss:0.40137
[71]	train-mlogloss:0.43587	eval-mlogloss:0.39652
[72]	train-mlogloss:0.43087	eval-mlogloss:0.39144
[73]	train-mlogloss:0.42672	eval-mlogloss:0.38647
[74]	train-mlogloss:0.42285	eval-mlogloss:0.38246
[75]	train-mlogloss:0.41813	eval-mlogloss:0.37743
[76]	train-mlogloss:0.41348	eval-mlogloss:0.37235
[77]	train-mlogloss:0.40921	eval-mlogloss:0.36786
[78]	train-mlogloss:0.40567	eval-mlogloss:0.36427
[79]	train-mlogloss:0.40115	eval-mlogloss:0.35928
[80]	train-mlogloss:0.39769	eval-mlogloss:0.35579
[81]	train-mlogloss:0.39491	eval-mlogloss:0.35316
[82]	train-mlogloss:0.39069	eval-mlogloss:0.34858
[83]	train-mlogloss:0.38722	eval-mlogloss:0.34438
[84]	train-mlogloss:0.38423	eval-mlogloss:0.34126
[85]	train-mlogloss:0.38071	eval-mlogloss:0.33753
[86]	train-mlogloss:0.37725	eval-mlogloss:0.33356
[87]	train-mlogloss:0.37407	eval-mlogloss:0.33008
[88]	train-mlogloss:0.37058	eval-mlogloss:0.32656
[89]	train-mlogloss:0.36700	eval-mlogloss:0.32280
[90]	train-mlogloss:0.36315	eval-mlogloss:0.31859
[91]	train-mlogloss:0.36034	eval-mlogloss:0.31539
[92]	train-mlogloss:0.35721	eval-mlogloss:0.31188
[93]	train-mlogloss:0.35407	eval-mlogloss:0.30834
[94]	train-mlogloss:0.35084	eval-mlogloss:0.30489
[95]	train-mlogloss:0.34751	eval-mlogloss:0.30094
[96]	train-mlogloss:0.34452	eval-mlogloss:0.29761
[97]	train-mlogloss:0.34147	eval-mlogloss:0.29455
[98]	train-mlogloss:0.33882	eval-mlogloss:0.29152
[99]	train-mlogloss:0.33635	eval-mlogloss:0.28880
[100]	train-mlogloss:0.33388	eval-mlogloss:0.28620
[101]	train-mlogloss:0.33086	eval-mlogloss:0.28275
[102]	train-mlogloss:0.32833	eval-mlogloss:0.27992
[103]	train-mlogloss:0.32579	eval-mlogloss:0.27698
[104]	train-mlogloss:0.32311	eval-mlogloss:0.27389
[105]	train-mlogloss:0.32074	eval-mlogloss:0.27136
[106]	train-mlogloss:0.31855	eval-mlogloss:0.26897
[107]	train-mlogloss:0.31657	eval-mlogloss:0.26658
[108]	train-mlogloss:0.31437	eval-mlogloss:0.26407
[109]	train-mlogloss:0.31238	eval-mlogloss:0.26188
[110]	train-mlogloss:0.31157	eval-mlogloss:0.26094
[111]	train-mlogloss:0.31000	eval-mlogloss:0.25926
[112]	train-mlogloss:0.30743	eval-mlogloss:0.25653
[113]	train-mlogloss:0.30524	eval-mlogloss:0.25391
[114]	train-mlogloss:0.30326	eval-mlogloss:0.25164
[115]	train-mlogloss:0.30054	eval-mlogloss:0.24872
[116]	train-mlogloss:0.29863	eval-mlogloss:0.24673
[117]	train-mlogloss:0.29665	eval-mlogloss:0.24466
[118]	train-mlogloss:0.29473	eval-mlogloss:0.24267
[119]	train-mlogloss:0.29260	eval-mlogloss:0.24039
[120]	train-mlogloss:0.29078	eval-mlogloss:0.23860
[121]	train-mlogloss:0.28921	eval-mlogloss:0.23683
[122]	train-mlogloss:0.28737	eval-mlogloss:0.23482
[123]	train-mlogloss:0.28602	eval-mlogloss:0.23356
[124]	train-mlogloss:0.28413	eval-mlogloss:0.23138
[125]	train-mlogloss:0.28229	eval-mlogloss:0.22933
[126]	train-mlogloss:0.28136	eval-mlogloss:0.22816
[127]	train-mlogloss:0.27962	eval-mlogloss:0.22634
[128]	train-mlogloss:0.27805	eval-mlogloss:0.22456
[129]	train-mlogloss:0.27725	eval-mlogloss:0.22360
[130]	train-mlogloss:0.27542	eval-mlogloss:0.22150
[131]	train-mlogloss:0.27385	eval-mlogloss:0.21965
[132]	train-mlogloss:0.27309	eval-mlogloss:0.21865
[133]	train-mlogloss:0.27126	eval-mlogloss:0.21657
[134]	train-mlogloss:0.26956	eval-mlogloss:0.21444
[135]	train-mlogloss:0.26798	eval-mlogloss:0.21282
[136]	train-mlogloss:0.26660	eval-mlogloss:0.21117
[137]	train-mlogloss:0.26514	eval-mlogloss:0.20951
[138]	train-mlogloss:0.26365	eval-mlogloss:0.20796
[139]	train-mlogloss:0.26301	eval-mlogloss:0.20740
[140]	train-mlogloss:0.26144	eval-mlogloss:0.20563
[141]	train-mlogloss:0.26071	eval-mlogloss:0.20475
[142]	train-mlogloss:0.26003	eval-mlogloss:0.20422
[143]	train-mlogloss:0.25830	eval-mlogloss:0.20239
[144]	train-mlogloss:0.25692	eval-mlogloss:0.20089
[145]	train-mlogloss:0.25612	eval-mlogloss:0.20002
[146]	train-mlogloss:0.25475	eval-mlogloss:0.19837
[147]	train-mlogloss:0.25331	eval-mlogloss:0.19676
[148]	train-mlogloss:0.25277	eval-mlogloss:0.19617
[149]	train-mlogloss:0.25198	eval-mlogloss:0.19513
[150]	train-mlogloss:0.25129	eval-mlogloss:0.19421
[151]	train-mlogloss:0.25036	eval-mlogloss:0.19319
[152]	train-mlogloss:0.24980	eval-mlogloss:0.19245
[153]	train-mlogloss:0.24851	eval-mlogloss:0.19091
[154]	train-mlogloss:0.24801	eval-mlogloss:0.19033
[155]	train-mlogloss:0.24748	eval-mlogloss:0.18970
[156]	train-mlogloss:0.24694	eval-mlogloss:0.18901
[157]	train-mlogloss:0.24621	eval-mlogloss:0.18817
[158]	train-mlogloss:0.24563	eval-mlogloss:0.18750
[159]	train-mlogloss:0.24501	eval-mlogloss:0.18654
[160]	train-mlogloss:0.24495	eval-mlogloss:0.18651
[161]	train-mlogloss:0.24486	eval-mlogloss:0.18621
[162]	train-mlogloss:0.24481	eval-mlogloss:0.18604
[163]	train-mlogloss:0.24464	eval-mlogloss:0.18600
[164]	train-mlogloss:0.24345	eval-mlogloss:0.18471
[165]	train-mlogloss:0.24290	eval-mlogloss:0.18387
[166]	train-mlogloss:0.24250	eval-mlogloss:0.18353
[167]	train-mlogloss:0.24199	eval-mlogloss:0.18293
[168]	train-mlogloss:0.24180	eval-mlogloss:0.18276
[169]	train-mlogloss:0.24172	eval-mlogloss:0.18251
[170]	train-mlogloss:0.24124	eval-mlogloss:0.18190
[171]	train-mlogloss:0.24073	eval-mlogloss:0.18135
[172]	train-mlogloss:0.24019	eval-mlogloss:0.18064
[173]	train-mlogloss:0.23962	eval-mlogloss:0.17991
[174]	train-mlogloss:0.23903	eval-mlogloss:0.17925
[175]	train-mlogloss:0.23860	eval-mlogloss:0.17864
[176]	train-mlogloss:0.23847	eval-mlogloss:0.17858
[177]	train-mlogloss:0.23838	eval-mlogloss:0.17842
[178]	train-mlogloss:0.23756	eval-mlogloss:0.17759
[179]	train-mlogloss:0.23749	eval-mlogloss:0.17748
[180]	train-mlogloss:0.23711	eval-mlogloss:0.17695
[181]	train-mlogloss:0.23711	eval-mlogloss:0.17698
[182]	train-mlogloss:0.23593	eval-mlogloss:0.17559
[183]	train-mlogloss:0.23482	eval-mlogloss:0.17441
[184]	train-mlogloss:0.23442	eval-mlogloss:0.17388
[185]	train-mlogloss:0.23440	eval-mlogloss:0.17392
[186]	train-mlogloss:0.23441	eval-mlogloss:0.17389
[187]	train-mlogloss:0.23396	eval-mlogloss:0.17336
[188]	train-mlogloss:0.23357	eval-mlogloss:0.17294
[189]	train-mlogloss:0.23351	eval-mlogloss:0.17274
[190]	train-mlogloss:0.23343	eval-mlogloss:0.17262
[191]	train-mlogloss:0.23317	eval-mlogloss:0.17227
[192]	train-mlogloss:0.23305	eval-mlogloss:0.17217
[193]	train-mlogloss:0.23301	eval-mlogloss:0.17206
[194]	train-mlogloss:0.23289	eval-mlogloss:0.17179
[195]	train-mlogloss:0.23282	eval-mlogloss:0.17169
[196]	train-mlogloss:0.23251	eval-mlogloss:0.17132
[197]	train-mlogloss:0.23248	eval-mlogloss:0.17129
[198]	train-mlogloss:0.23215	eval-mlogloss:0.17087
[199]	train-mlogloss:0.23101	eval-mlogloss:0.16963
[200]	train-mlogloss:0.23073	eval-mlogloss:0.16924
[201]	train-mlogloss:0.23045	eval-mlogloss:0.16887
[202]	train-mlogloss:0.23037	eval-mlogloss:0.16875
[203]	train-mlogloss:0.23032	eval-mlogloss:0.16873
[204]	train-mlogloss:0.23024	eval-mlogloss:0.16871
[205]	train-mlogloss:0.22983	eval-mlogloss:0.16824
[206]	train-mlogloss:0.22980	eval-mlogloss:0.16810
[207]	train-mlogloss:0.22975	eval-mlogloss:0.16801
[208]	train-mlogloss:0.22967	eval-mlogloss:0.16792
[209]	train-mlogloss:0.22921	eval-mlogloss:0.16717
[210]	train-mlogloss:0.22917	eval-mlogloss:0.16715
[211]	train-mlogloss:0.22879	eval-mlogloss:0.16670
[212]	train-mlogloss:0.22864	eval-mlogloss:0.16652
[213]	train-mlogloss:0.22836	eval-mlogloss:0.16616
[214]	train-mlogloss:0.22830	eval-mlogloss:0.16614
[215]	train-mlogloss:0.22811	eval-mlogloss:0.16594
[216]	train-mlogloss:0.22807	eval-mlogloss:0.16590
[217]	train-mlogloss:0.22796	eval-mlogloss:0.16595
[218]	train-mlogloss:0.22755	eval-mlogloss:0.16534
[219]	train-mlogloss:0.22704	eval-mlogloss:0.16470
[220]	train-mlogloss:0.22704	eval-mlogloss:0.16470
[221]	train-mlogloss:0.22662	eval-mlogloss:0.16422
[222]	train-mlogloss:0.22661	eval-mlogloss:0.16422
[223]	train-mlogloss:0.22644	eval-mlogloss:0.16401
[224]	train-mlogloss:0.22642	eval-mlogloss:0.16399
[225]	train-mlogloss:0.22640	eval-mlogloss:0.16401
[226]	train-mlogloss:0.22641	eval-mlogloss:0.16401
[227]	train-mlogloss:0.22636	eval-mlogloss:0.16397
[228]	train-mlogloss:0.22589	eval-mlogloss:0.16335
[229]	train-mlogloss:0.22582	eval-mlogloss:0.16329
[230]	train-mlogloss:0.22525	eval-mlogloss:0.16262
[231]	train-mlogloss:0.22519	eval-mlogloss:0.16257
[232]	train-mlogloss:0.22514	eval-mlogloss:0.16257
[233]	train-mlogloss:0.22511	eval-mlogloss:0.16249
[234]	train-mlogloss:0.22513	eval-mlogloss:0.16254
[235]	train-mlogloss:0.22473	eval-mlogloss:0.16204
[236]	train-mlogloss:0.22463	eval-mlogloss:0.16189
[237]	train-mlogloss:0.22459	eval-mlogloss:0.16184
[238]	train-mlogloss:0.22455	eval-mlogloss:0.16168
[239]	train-mlogloss:0.22453	eval-mlogloss:0.16164
[240]	train-mlogloss:0.22454	eval-mlogloss:0.16163
[241]	train-mlogloss:0.22408	eval-mlogloss:0.16112
[242]	train-mlogloss:0.22405	eval-mlogloss:0.16111
[243]	train-mlogloss:0.22371	eval-mlogloss:0.16060
[244]	train-mlogloss:0.22363	eval-mlogloss:0.16057
[245]	train-mlogloss:0.22359	eval-mlogloss:0.16042
[246]	train-mlogloss:0.22358	eval-mlogloss:0.16042
[247]	train-mlogloss:0.22355	eval-mlogloss:0.16045
[248]	train-mlogloss:0.22351	eval-mlogloss:0.16031
[249]	train-mlogloss:0.22346	eval-mlogloss:0.16028
[250]	train-mlogloss:0.22344	eval-mlogloss:0.16024
[251]	train-mlogloss:0.22340	eval-mlogloss:0.16022
[252]	train-mlogloss:0.22336	eval-mlogloss:0.16021
[253]	train-mlogloss:0.22282	eval-mlogloss:0.15949
[254]	train-mlogloss:0.22284	eval-mlogloss:0.15954
[255]	train-mlogloss:0.22281	eval-mlogloss:0.15948
[256]	train-mlogloss:0.22251	eval-mlogloss:0.15905
[257]	train-mlogloss:0.22245	eval-mlogloss:0.15896
[258]	train-mlogloss:0.22241	eval-mlogloss:0.15893
[259]	train-mlogloss:0.22236	eval-mlogloss:0.15886
[260]	train-mlogloss:0.22234	eval-mlogloss:0.15883
[261]	train-mlogloss:0.22230	eval-mlogloss:0.15881
[262]	train-mlogloss:0.22227	eval-mlogloss:0.15870
[263]	train-mlogloss:0.22220	eval-mlogloss:0.15860
[264]	train-mlogloss:0.22189	eval-mlogloss:0.15826
[265]	train-mlogloss:0.22186	eval-mlogloss:0.15824
[266]	train-mlogloss:0.22158	eval-mlogloss:0.15787
[267]	train-mlogloss:0.22157	eval-mlogloss:0.15787
[268]	train-mlogloss:0.22160	eval-mlogloss:0.15791
[269]	train-mlogloss:0.22154	eval-mlogloss:0.15783
[270]	train-mlogloss:0.22111	eval-mlogloss:0.15721
[271]	train-mlogloss:0.22110	eval-mlogloss:0.15721
[272]	train-mlogloss:0.22105	eval-mlogloss:0.15701
[273]	train-mlogloss:0.22098	eval-mlogloss:0.15694
[274]	train-mlogloss:0.22096	eval-mlogloss:0.15692
[275]	train-mlogloss:0.22004	eval-mlogloss:0.15605
[276]	train-mlogloss:0.22004	eval-mlogloss:0.15605
[277]	train-mlogloss:0.22004	eval-mlogloss:0.15603
[278]	train-mlogloss:0.22004	eval-mlogloss:0.15601
[279]	train-mlogloss:0.22004	eval-mlogloss:0.15601
[280]	train-mlogloss:0.22004	eval-mlogloss:0.15601
[281]	train-mlogloss:0.22000	eval-mlogloss:0.15596
[282]	train-mlogloss:0.22000	eval-mlogloss:0.15594
[283]	train-mlogloss:0.21996	eval-mlogloss:0.15583
[284]	train-mlogloss:0.21995	eval-mlogloss:0.15580
[285]	train-mlogloss:0.21990	eval-mlogloss:0.15578
[286]	train-mlogloss:0.21990	eval-mlogloss:0.15579
[287]	train-mlogloss:0.21984	eval-mlogloss:0.15575
[288]	train-mlogloss:0.21984	eval-mlogloss:0.15575
[289]	train-mlogloss:0.21983	eval-mlogloss:0.15572
[290]	train-mlogloss:0.21982	eval-mlogloss:0.15571
[291]	train-mlogloss:0.21940	eval-mlogloss:0.15499
[292]	train-mlogloss:0.21898	eval-mlogloss:0.15446
[293]	train-mlogloss:0.21898	eval-mlogloss:0.15446
[294]	train-mlogloss:0.21894	eval-mlogloss:0.15444
[295]	train-mlogloss:0.21890	eval-mlogloss:0.15440
[296]	train-mlogloss:0.21886	eval-mlogloss:0.15437
[297]	train-mlogloss:0.21883	eval-mlogloss:0.15437
[298]	train-mlogloss:0.21883	eval-mlogloss:0.15437
[299]	train-mlogloss:0.21875	eval-mlogloss:0.15431

[I 2026-06-28 16:06:29,987] Trial 21 finished with value: 1.0 and parameters: {'lambda': 0.022272654506274196, 'alpha': 2.7196773953419404e-05, 'eta': 0.013382424359024606, 'gamma': 0.04399845055821829, 'max_depth': 5, 'min_child_weight': 6, 'subsample': 0.5295237496105143, 'colsample_bytree': 0.917833224245952}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:1.08511	eval-mlogloss:1.08674
[1]	train-mlogloss:1.07178	eval-mlogloss:1.07320
[2]	train-mlogloss:1.05864	eval-mlogloss:1.05925
[3]	train-mlogloss:1.04602	eval-mlogloss:1.04523
[4]	train-mlogloss:1.03283	eval-mlogloss:1.03160
[5]	train-mlogloss:1.01982	eval-mlogloss:1.01750
[6]	train-mlogloss:1.00801	eval-mlogloss:1.00453
[7]	train-mlogloss:0.99603	eval-mlogloss:0.99162
[8]	train-mlogloss:0.98379	eval-mlogloss:0.97911
[9]	train-mlogloss:0.97322	eval-mlogloss:0.96819
[10]	train-mlogloss:0.96507	eval-mlogloss:0.95911
[11]	train-mlogloss:0.95383	eval-mlogloss:0.94733
[12]	train-mlogloss:0.94224	eval-mlogloss:0.93478
[13]	train-mlogloss:0.93136	eval-mlogloss:0.92358
[14]	train-mlogloss:0.92036	eval-mlogloss:0.91209
[15]	train-mlogloss:0.90994	eval-mlogloss:0.90084
[16]	train-mlogloss:0.89959	eval-mlogloss:0.89005
[17]	train-mlogloss:0.88875	eval-mlogloss:0.87871
[18]	train-mlogloss:0.87849	eval-mlogloss:0.86800
[19]	train-mlogloss:0.86861	eval-mlogloss:0.85732
[20]	train-mlogloss:0.85876	eval-mlogloss:0.84673
[21]	train-mlogloss:0.84888	eval-mlogloss:0.83616
[22]	train-mlogloss:0.83986	eval-mlogloss:0.82644
[23]	train-mlogloss:0.83076	eval-mlogloss:0.81706
[24]	train-mlogloss:0.82245	eval-mlogloss:0.80852
[25]	train-mlogloss:0.81314	eval-mlogloss:0.79892
[26]	train-mlogloss:0.80367	eval-mlogloss:0.78836
[27]	train-mlogloss:0.79427	eval-mlogloss:0.77860
[28]	train-mlogloss:0.78612	eval-mlogloss:0.76970
[29]	train-mlogloss:0.77744	eval-mlogloss:0.76042
[30]	train-mlogloss:0.76972	eval-mlogloss:0.75191
[31]	train-mlogloss:0.76084	eval-mlogloss:0.74230
[32]	train-mlogloss:0.75306	eval-mlogloss:0.73442
[33]	train-mlogloss:0.74476	eval-mlogloss:0.72532
[34]	train-mlogloss:0.73668	eval-mlogloss:0.71676
[35]	train-mlogloss:0.72882	eval-mlogloss:0.70812
[36]	train-mlogloss:0.72167	eval-mlogloss:0.70056
[37]	train-mlogloss:0.71466	eval-mlogloss:0.69319
[38]	train-mlogloss:0.70693	eval-mlogloss:0.68489
[39]	train-mlogloss:0.70154	eval-mlogloss:0.67852
[40]	train-mlogloss:0.69415	eval-mlogloss:0.67057
[41]	train-mlogloss:0.68639	eval-mlogloss:0.66212
[42]	train-mlogloss:0.67923	eval-mlogloss:0.65432
[43]	train-mlogloss:0.67309	eval-mlogloss:0.64826
[44]	train-mlogloss:0.66621	eval-mlogloss:0.64130
[45]	train-mlogloss:0.65949	eval-mlogloss:0.63388
[46]	train-mlogloss:0.65369	eval-mlogloss:0.62724
[47]	train-mlogloss:0.64678	eval-mlogloss:0.62008
[48]	train-mlogloss:0.63999	eval-mlogloss:0.61325
[49]	train-mlogloss:0.63316	eval-mlogloss:0.60595
[50]	train-mlogloss:0.62667	eval-mlogloss:0.59895
[51]	train-mlogloss:0.62045	eval-mlogloss:0.59211
[52]	train-mlogloss:0.61424	eval-mlogloss:0.58526
[53]	train-mlogloss:0.60810	eval-mlogloss:0.57838
[54]	train-mlogloss:0.60327	eval-mlogloss:0.57314
[55]	train-mlogloss:0.59709	eval-mlogloss:0.56632
[56]	train-mlogloss:0.59298	eval-mlogloss:0.56225
[57]	train-mlogloss:0.58762	eval-mlogloss:0.55650
[58]	train-mlogloss:0.58190	eval-mlogloss:0.55030
[59]	train-mlogloss:0.57677	eval-mlogloss:0.54537
[60]	train-mlogloss:0.57134	eval-mlogloss:0.53938
[61]	train-mlogloss:0.56628	eval-mlogloss:0.53392
[62]	train-mlogloss:0.56072	eval-mlogloss:0.52767
[63]	train-mlogloss:0.55531	eval-mlogloss:0.52173
[64]	train-mlogloss:0.55015	eval-mlogloss:0.51613
[65]	train-mlogloss:0.54592	eval-mlogloss:0.51195
[66]	train-mlogloss:0.54221	eval-mlogloss:0.50792
[67]	train-mlogloss:0.53706	eval-mlogloss:0.50243
[68]	train-mlogloss:0.53186	eval-mlogloss:0.49710
[69]	train-mlogloss:0.52668	eval-mlogloss:0.49139
[70]	train-mlogloss:0.52180	eval-mlogloss:0.48606
[71]	train-mlogloss:0.51796	eval-mlogloss:0.48227
[72]	train-mlogloss:0.51406	eval-mlogloss:0.47847
[73]	train-mlogloss:0.51076	eval-mlogloss:0.47464
[74]	train-mlogloss:0.50654	eval-mlogloss:0.47030
[75]	train-mlogloss:0.50187	eval-mlogloss:0.46520
[76]	train-mlogloss:0.49702	eval-mlogloss:0.45974
[77]	train-mlogloss:0.49305	eval-mlogloss:0.45545
[78]	train-mlogloss:0.48925	eval-mlogloss:0.45144
[79]	train-mlogloss:0.48495	eval-mlogloss:0.44681
[80]	train-mlogloss:0.48076	eval-mlogloss:0.44219
[81]	train-mlogloss:0.47684	eval-mlogloss:0.43837
[82]	train-mlogloss:0.47279	eval-mlogloss:0.43438
[83]	train-mlogloss:0.46895	eval-mlogloss:0.43010
[84]	train-mlogloss:0.46569	eval-mlogloss:0.42670
[85]	train-mlogloss:0.46203	eval-mlogloss:0.42267
[86]	train-mlogloss:0.45808	eval-mlogloss:0.41832
[87]	train-mlogloss:0.45443	eval-mlogloss:0.41452
[88]	train-mlogloss:0.45070	eval-mlogloss:0.41072
[89]	train-mlogloss:0.44692	eval-mlogloss:0.40652
[90]	train-mlogloss:0.44280	eval-mlogloss:0.40205
[91]	train-mlogloss:0.44002	eval-mlogloss:0.39936
[92]	train-mlogloss:0.43668	eval-mlogloss:0.39570
[93]	train-mlogloss:0.43297	eval-mlogloss:0.39174
[94]	train-mlogloss:0.42950	eval-mlogloss:0.38817
[95]	train-mlogloss:0.42640	eval-mlogloss:0.38504
[96]	train-mlogloss:0.42290	eval-mlogloss:0.38118
[97]	train-mlogloss:0.41957	eval-mlogloss:0.37774
[98]	train-mlogloss:0.41736	eval-mlogloss:0.37536
[99]	train-mlogloss:0.41471	eval-mlogloss:0.37233
[100]	train-mlogloss:0.41120	eval-mlogloss:0.36860
[101]	train-mlogloss:0.40772	eval-mlogloss:0.36485
[102]	train-mlogloss:0.40465	eval-mlogloss:0.36197
[103]	train-mlogloss:0.40149	eval-mlogloss:0.35834
[104]	train-mlogloss:0.39841	eval-mlogloss:0.35497
[105]	train-mlogloss:0.39576	eval-mlogloss:0.35217
[106]	train-mlogloss:0.39279	eval-mlogloss:0.34896
[107]	train-mlogloss:0.38992	eval-mlogloss:0.34596
[108]	train-mlogloss:0.38719	eval-mlogloss:0.34305
[109]	train-mlogloss:0.38438	eval-mlogloss:0.33963
[110]	train-mlogloss:0.38265	eval-mlogloss:0.33752
[111]	train-mlogloss:0.38033	eval-mlogloss:0.33495
[112]	train-mlogloss:0.37755	eval-mlogloss:0.33198
[113]	train-mlogloss:0.37517	eval-mlogloss:0.32911
[114]	train-mlogloss:0.37314	eval-mlogloss:0.32687
[115]	train-mlogloss:0.37013	eval-mlogloss:0.32360
[116]	train-mlogloss:0.36757	eval-mlogloss:0.32070
[117]	train-mlogloss:0.36539	eval-mlogloss:0.31841
[118]	train-mlogloss:0.36281	eval-mlogloss:0.31571
[119]	train-mlogloss:0.36015	eval-mlogloss:0.31293
[120]	train-mlogloss:0.35780	eval-mlogloss:0.31059
[121]	train-mlogloss:0.35578	eval-mlogloss:0.30860
[122]	train-mlogloss:0.35363	eval-mlogloss:0.30609
[123]	train-mlogloss:0.35209	eval-mlogloss:0.30461
[124]	train-mlogloss:0.34998	eval-mlogloss:0.30248
[125]	train-mlogloss:0.34797	eval-mlogloss:0.30050
[126]	train-mlogloss:0.34566	eval-mlogloss:0.29769
[127]	train-mlogloss:0.34385	eval-mlogloss:0.29592
[128]	train-mlogloss:0.34140	eval-mlogloss:0.29331
[129]	train-mlogloss:0.33989	eval-mlogloss:0.29179
[130]	train-mlogloss:0.33778	eval-mlogloss:0.28938
[131]	train-mlogloss:0.33594	eval-mlogloss:0.28733
[132]	train-mlogloss:0.33489	eval-mlogloss:0.28596
[133]	train-mlogloss:0.33292	eval-mlogloss:0.28374
[134]	train-mlogloss:0.33094	eval-mlogloss:0.28129
[135]	train-mlogloss:0.32889	eval-mlogloss:0.27908
[136]	train-mlogloss:0.32673	eval-mlogloss:0.27662
[137]	train-mlogloss:0.32504	eval-mlogloss:0.27467
[138]	train-mlogloss:0.32341	eval-mlogloss:0.27294
[139]	train-mlogloss:0.32157	eval-mlogloss:0.27122
[140]	train-mlogloss:0.31981	eval-mlogloss:0.26920
[141]	train-mlogloss:0.31804	eval-mlogloss:0.26731
[142]	train-mlogloss:0.31634	eval-mlogloss:0.26556
[143]	train-mlogloss:0.31446	eval-mlogloss:0.26369
[144]	train-mlogloss:0.31288	eval-mlogloss:0.26198
[145]	train-mlogloss:0.31136	eval-mlogloss:0.26036
[146]	train-mlogloss:0.30986	eval-mlogloss:0.25866
[147]	train-mlogloss:0.30816	eval-mlogloss:0.25676
[148]	train-mlogloss:0.30756	eval-mlogloss:0.25603
[149]	train-mlogloss:0.30575	eval-mlogloss:0.25399
[150]	train-mlogloss:0.30429	eval-mlogloss:0.25231
[151]	train-mlogloss:0.30289	eval-mlogloss:0.25083
[152]	train-mlogloss:0.30232	eval-mlogloss:0.25009
[153]	train-mlogloss:0.30118	eval-mlogloss:0.24886
[154]	train-mlogloss:0.29963	eval-mlogloss:0.24725
[155]	train-mlogloss:0.29808	eval-mlogloss:0.24553
[156]	train-mlogloss:0.29671	eval-mlogloss:0.24400
[157]	train-mlogloss:0.29501	eval-mlogloss:0.24223
[158]	train-mlogloss:0.29432	eval-mlogloss:0.24137
[159]	train-mlogloss:0.29357	eval-mlogloss:0.24036
[160]	train-mlogloss:0.29214	eval-mlogloss:0.23878
[161]	train-mlogloss:0.29121	eval-mlogloss:0.23789
[162]	train-mlogloss:0.29043	eval-mlogloss:0.23715
[163]	train-mlogloss:0.28932	eval-mlogloss:0.23588
[164]	train-mlogloss:0.28868	eval-mlogloss:0.23523
[165]	train-mlogloss:0.28732	eval-mlogloss:0.23373
[166]	train-mlogloss:0.28610	eval-mlogloss:0.23241
[167]	train-mlogloss:0.28541	eval-mlogloss:0.23141
[168]	train-mlogloss:0.28401	eval-mlogloss:0.22991
[169]	train-mlogloss:0.28389	eval-mlogloss:0.22974
[170]	train-mlogloss:0.28273	eval-mlogloss:0.22845
[171]	train-mlogloss:0.28209	eval-mlogloss:0.22768
[172]	train-mlogloss:0.28082	eval-mlogloss:0.22655
[173]	train-mlogloss:0.27983	eval-mlogloss:0.22536
[174]	train-mlogloss:0.27928	eval-mlogloss:0.22474
[175]	train-mlogloss:0.27873	eval-mlogloss:0.22409
[176]	train-mlogloss:0.27775	eval-mlogloss:0.22300
[177]	train-mlogloss:0.27720	eval-mlogloss:0.22228
[178]	train-mlogloss:0.27585	eval-mlogloss:0.22072
[179]	train-mlogloss:0.27487	eval-mlogloss:0.21960
[180]	train-mlogloss:0.27440	eval-mlogloss:0.21901
[181]	train-mlogloss:0.27374	eval-mlogloss:0.21834
[182]	train-mlogloss:0.27310	eval-mlogloss:0.21766
[183]	train-mlogloss:0.27197	eval-mlogloss:0.21647
[184]	train-mlogloss:0.27150	eval-mlogloss:0.21593
[185]	train-mlogloss:0.27024	eval-mlogloss:0.21452
[186]	train-mlogloss:0.26983	eval-mlogloss:0.21410
[187]	train-mlogloss:0.26921	eval-mlogloss:0.21337
[188]	train-mlogloss:0.26808	eval-mlogloss:0.21215
[189]	train-mlogloss:0.26732	eval-mlogloss:0.21130
[190]	train-mlogloss:0.26720	eval-mlogloss:0.21119
[191]	train-mlogloss:0.26649	eval-mlogloss:0.21052
[192]	train-mlogloss:0.26533	eval-mlogloss:0.20936
[193]	train-mlogloss:0.26480	eval-mlogloss:0.20870
[194]	train-mlogloss:0.26425	eval-mlogloss:0.20799
[195]	train-mlogloss:0.26415	eval-mlogloss:0.20784
[196]	train-mlogloss:0.26380	eval-mlogloss:0.20739
[197]	train-mlogloss:0.26335	eval-mlogloss:0.20685
[198]	train-mlogloss:0.26299	eval-mlogloss:0.20635
[199]	train-mlogloss:0.26272	eval-mlogloss:0.20602
[200]	train-mlogloss:0.26237	eval-mlogloss:0.20561
[201]	train-mlogloss:0.26237	eval-mlogloss:0.20562
[202]	train-mlogloss:0.26169	eval-mlogloss:0.20497
[203]	train-mlogloss:0.26132	eval-mlogloss:0.20460
[204]	train-mlogloss:0.26079	eval-mlogloss:0.20396
[205]	train-mlogloss:0.26018	eval-mlogloss:0.20315
[206]	train-mlogloss:0.26018	eval-mlogloss:0.20315
[207]	train-mlogloss:0.25961	eval-mlogloss:0.20260
[208]	train-mlogloss:0.25892	eval-mlogloss:0.20178
[209]	train-mlogloss:0.25798	eval-mlogloss:0.20066
[210]	train-mlogloss:0.25798	eval-mlogloss:0.20068
[211]	train-mlogloss:0.25735	eval-mlogloss:0.19989
[212]	train-mlogloss:0.25683	eval-mlogloss:0.19927
[213]	train-mlogloss:0.25647	eval-mlogloss:0.19883
[214]	train-mlogloss:0.25647	eval-mlogloss:0.19884
[215]	train-mlogloss:0.25613	eval-mlogloss:0.19850
[216]	train-mlogloss:0.25613	eval-mlogloss:0.19850
[217]	train-mlogloss:0.25562	eval-mlogloss:0.19791
[218]	train-mlogloss:0.25456	eval-mlogloss:0.19677
[219]	train-mlogloss:0.25407	eval-mlogloss:0.19618
[220]	train-mlogloss:0.25407	eval-mlogloss:0.19619
[221]	train-mlogloss:0.25381	eval-mlogloss:0.19587
[222]	train-mlogloss:0.25284	eval-mlogloss:0.19470
[223]	train-mlogloss:0.25205	eval-mlogloss:0.19385
[224]	train-mlogloss:0.25205	eval-mlogloss:0.19385
[225]	train-mlogloss:0.25205	eval-mlogloss:0.19385
[226]	train-mlogloss:0.25114	eval-mlogloss:0.19289
[227]	train-mlogloss:0.25113	eval-mlogloss:0.19287
[228]	train-mlogloss:0.25068	eval-mlogloss:0.19222
[229]	train-mlogloss:0.25008	eval-mlogloss:0.19140
[230]	train-mlogloss:0.24966	eval-mlogloss:0.19092
[231]	train-mlogloss:0.24907	eval-mlogloss:0.19026
[232]	train-mlogloss:0.24907	eval-mlogloss:0.19028
[233]	train-mlogloss:0.24907	eval-mlogloss:0.19026
[234]	train-mlogloss:0.24907	eval-mlogloss:0.19028
[235]	train-mlogloss:0.24860	eval-mlogloss:0.18973
[236]	train-mlogloss:0.24831	eval-mlogloss:0.18937
[237]	train-mlogloss:0.24789	eval-mlogloss:0.18894
[238]	train-mlogloss:0.24710	eval-mlogloss:0.18807
[239]	train-mlogloss:0.24711	eval-mlogloss:0.18807
[240]	train-mlogloss:0.24711	eval-mlogloss:0.18806
[241]	train-mlogloss:0.24668	eval-mlogloss:0.18749
[242]	train-mlogloss:0.24617	eval-mlogloss:0.18690
[243]	train-mlogloss:0.24576	eval-mlogloss:0.18638
[244]	train-mlogloss:0.24576	eval-mlogloss:0.18638
[245]	train-mlogloss:0.24575	eval-mlogloss:0.18639
[246]	train-mlogloss:0.24570	eval-mlogloss:0.18635
[247]	train-mlogloss:0.24569	eval-mlogloss:0.18633
[248]	train-mlogloss:0.24569	eval-mlogloss:0.18632
[249]	train-mlogloss:0.24569	eval-mlogloss:0.18631
[250]	train-mlogloss:0.24569	eval-mlogloss:0.18633
[251]	train-mlogloss:0.24569	eval-mlogloss:0.18633
[252]	train-mlogloss:0.24537	eval-mlogloss:0.18602
[253]	train-mlogloss:0.24481	eval-mlogloss:0.18527
[254]	train-mlogloss:0.24482	eval-mlogloss:0.18527
[255]	train-mlogloss:0.24427	eval-mlogloss:0.18470
[256]	train-mlogloss:0.24403	eval-mlogloss:0.18434
[257]	train-mlogloss:0.24403	eval-mlogloss:0.18435
[258]	train-mlogloss:0.24403	eval-mlogloss:0.18434
[259]	train-mlogloss:0.24404	eval-mlogloss:0.18434
[260]	train-mlogloss:0.24403	eval-mlogloss:0.18436
[261]	train-mlogloss:0.24404	eval-mlogloss:0.18436
[262]	train-mlogloss:0.24397	eval-mlogloss:0.18415
[263]	train-mlogloss:0.24387	eval-mlogloss:0.18400
[264]	train-mlogloss:0.24380	eval-mlogloss:0.18406
[265]	train-mlogloss:0.24359	eval-mlogloss:0.18379
[266]	train-mlogloss:0.24359	eval-mlogloss:0.18379
[267]	train-mlogloss:0.24347	eval-mlogloss:0.18367
[268]	train-mlogloss:0.24298	eval-mlogloss:0.18301
[269]	train-mlogloss:0.24298	eval-mlogloss:0.18301
[270]	train-mlogloss:0.24260	eval-mlogloss:0.18249
[271]	train-mlogloss:0.24259	eval-mlogloss:0.18250
[272]	train-mlogloss:0.24259	eval-mlogloss:0.18249
[273]	train-mlogloss:0.24259	eval-mlogloss:0.18247
[274]	train-mlogloss:0.24259	eval-mlogloss:0.18247
[275]	train-mlogloss:0.24163	eval-mlogloss:0.18152
[276]	train-mlogloss:0.24164	eval-mlogloss:0.18151
[277]	train-mlogloss:0.24163	eval-mlogloss:0.18150
[278]	train-mlogloss:0.24163	eval-mlogloss:0.18149
[279]	train-mlogloss:0.24163	eval-mlogloss:0.18148
[280]	train-mlogloss:0.24163	eval-mlogloss:0.18149
[281]	train-mlogloss:0.24163	eval-mlogloss:0.18149
[282]	train-mlogloss:0.24163	eval-mlogloss:0.18147
[283]	train-mlogloss:0.24162	eval-mlogloss:0.18148
[284]	train-mlogloss:0.24103	eval-mlogloss:0.18092
[285]	train-mlogloss:0.24103	eval-mlogloss:0.18093
[286]	train-mlogloss:0.24103	eval-mlogloss:0.18093
[287]	train-mlogloss:0.24103	eval-mlogloss:0.18094
[288]	train-mlogloss:0.24103	eval-mlogloss:0.18093
[289]	train-mlogloss:0.24062	eval-mlogloss:0.18039
[290]	train-mlogloss:0.24032	eval-mlogloss:0.18021
[291]	train-mlogloss:0.23985	eval-mlogloss:0.17966
[292]	train-mlogloss:0.23955	eval-mlogloss:0.17921
[293]	train-mlogloss:0.23955	eval-mlogloss:0.17921
[294]	train-mlogloss:0.23954	eval-mlogloss:0.17920
[295]	train-mlogloss:0.23954	eval-mlogloss:0.17920
[296]	train-mlogloss:0.23946	eval-mlogloss:0.17914
[297]	train-mlogloss:0.23947	eval-mlogloss:0.17915
[298]	train-mlogloss:0.23946	eval-mlogloss:0.17915
[299]	train-mlogloss:0.23935	eval-mlogloss:0.17906

[I 2026-06-28 16:06:30,422] Trial 22 finished with value: 1.0 and parameters: {'lambda': 0.15446764136748653, 'alpha': 6.0752238484889455e-06, 'eta': 0.010961342614548057, 'gamma': 0.6070148665097965, 'max_depth': 6, 'min_child_weight': 5, 'subsample': 0.41080869280849425, 'colsample_bytree': 0.9837289932760632}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:1.04144	eval-mlogloss:1.04182
[1]	train-mlogloss:0.98706	eval-mlogloss:0.98642

[I 2026-06-28 16:06:30,437] Trial 23 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.99258	eval-mlogloss:0.98805
[1]	train-mlogloss:0.90154	eval-mlogloss:0.89534

[I 2026-06-28 16:06:30,453] Trial 24 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.03914	eval-mlogloss:1.03966
[1]	train-mlogloss:0.98048	eval-mlogloss:0.97876

[I 2026-06-28 16:06:30,469] Trial 25 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.98725	eval-mlogloss:0.98917
[1]	train-mlogloss:0.88993	eval-mlogloss:0.88953

[I 2026-06-28 16:06:30,484] Trial 26 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.06138	eval-mlogloss:1.06152
[1]	train-mlogloss:1.02648	eval-mlogloss:1.02595
[2]	train-mlogloss:0.99305	eval-mlogloss:0.98987
[3]	train-mlogloss:0.96184	eval-mlogloss:0.95700
[4]	train-mlogloss:0.93146	eval-mlogloss:0.92556
[5]	train-mlogloss:0.90233	eval-mlogloss:0.89563
[6]	train-mlogloss:0.87538	eval-mlogloss:0.86555
[7]	train-mlogloss:0.84909	eval-mlogloss:0.83783

[I 2026-06-28 16:06:30,509] Trial 27 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:0.95288	eval-mlogloss:0.94800
[1]	train-mlogloss:0.82519	eval-mlogloss:0.81576

[I 2026-06-28 16:06:30,526] Trial 28 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.78666	eval-mlogloss:0.76850
[1]	train-mlogloss:0.59035	eval-mlogloss:0.56968

[I 2026-06-28 16:06:30,543] Trial 29 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.02056	eval-mlogloss:1.02041
[1]	train-mlogloss:0.94547	eval-mlogloss:0.94232

[I 2026-06-28 16:06:30,560] Trial 30 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.08544	eval-mlogloss:1.08718
[1]	train-mlogloss:1.07208	eval-mlogloss:1.07357
[2]	train-mlogloss:1.05858	eval-mlogloss:1.05931
[3]	train-mlogloss:1.04542	eval-mlogloss:1.04519
[4]	train-mlogloss:1.03275	eval-mlogloss:1.03213
[5]	train-mlogloss:1.02014	eval-mlogloss:1.01819
[6]	train-mlogloss:1.00837	eval-mlogloss:1.00573
[7]	train-mlogloss:0.99619	eval-mlogloss:0.99273
[8]	train-mlogloss:0.98420	eval-mlogloss:0.98010
[9]	train-mlogloss:0.97236	eval-mlogloss:0.96794
[10]	train-mlogloss:0.96313	eval-mlogloss:0.95793
[11]	train-mlogloss:0.95393	eval-mlogloss:0.94799
[12]	train-mlogloss:0.94244	eval-mlogloss:0.93580
[13]	train-mlogloss:0.93096	eval-mlogloss:0.92401
[14]	train-mlogloss:0.91964	eval-mlogloss:0.91216
[15]	train-mlogloss:0.90925	eval-mlogloss:0.90129
[16]	train-mlogloss:0.89901	eval-mlogloss:0.89037
[17]	train-mlogloss:0.88871	eval-mlogloss:0.87965
[18]	train-mlogloss:0.87836	eval-mlogloss:0.86906
[19]	train-mlogloss:0.86845	eval-mlogloss:0.85836
[20]	train-mlogloss:0.85866	eval-mlogloss:0.84784
[21]	train-mlogloss:0.84910	eval-mlogloss:0.83757
[22]	train-mlogloss:0.84162	eval-mlogloss:0.82937
[23]	train-mlogloss:0.83261	eval-mlogloss:0.82019
[24]	train-mlogloss:0.82366	eval-mlogloss:0.81067
[25]	train-mlogloss:0.81445	eval-mlogloss:0.80118
[26]	train-mlogloss:0.80508	eval-mlogloss:0.79074
[27]	train-mlogloss:0.79580	eval-mlogloss:0.78094
[28]	train-mlogloss:0.78754	eval-mlogloss:0.77183
[29]	train-mlogloss:0.77904	eval-mlogloss:0.76293
[30]	train-mlogloss:0.77059	eval-mlogloss:0.75364
[31]	train-mlogloss:0.76240	eval-mlogloss:0.74503
[32]	train-mlogloss:0.75442	eval-mlogloss:0.73649
[33]	train-mlogloss:0.74612	eval-mlogloss:0.72742
[34]	train-mlogloss:0.73808	eval-mlogloss:0.71906
[35]	train-mlogloss:0.73043	eval-mlogloss:0.71072
[36]	train-mlogloss:0.72296	eval-mlogloss:0.70295
[37]	train-mlogloss:0.71588	eval-mlogloss:0.69593
[38]	train-mlogloss:0.70829	eval-mlogloss:0.68789
[39]	train-mlogloss:0.70070	eval-mlogloss:0.67993
[40]	train-mlogloss:0.69359	eval-mlogloss:0.67226
[41]	train-mlogloss:0.68630	eval-mlogloss:0.66466
[42]	train-mlogloss:0.67907	eval-mlogloss:0.65694
[43]	train-mlogloss:0.67196	eval-mlogloss:0.64914
[44]	train-mlogloss:0.66514	eval-mlogloss:0.64222
[45]	train-mlogloss:0.65843	eval-mlogloss:0.63496
[46]	train-mlogloss:0.65134	eval-mlogloss:0.62714
[47]	train-mlogloss:0.64471	eval-mlogloss:0.62027
[48]	train-mlogloss:0.63791	eval-mlogloss:0.61302
[49]	train-mlogloss:0.63136	eval-mlogloss:0.60594
[50]	train-mlogloss:0.62488	eval-mlogloss:0.59904
[51]	train-mlogloss:0.61978	eval-mlogloss:0.59354
[52]	train-mlogloss:0.61353	eval-mlogloss:0.58707
[53]	train-mlogloss:0.60727	eval-mlogloss:0.58029
[54]	train-mlogloss:0.60123	eval-mlogloss:0.57382
[55]	train-mlogloss:0.59497	eval-mlogloss:0.56686
[56]	train-mlogloss:0.58911	eval-mlogloss:0.56064
[57]	train-mlogloss:0.58354	eval-mlogloss:0.55489
[58]	train-mlogloss:0.57766	eval-mlogloss:0.54850
[59]	train-mlogloss:0.57201	eval-mlogloss:0.54250
[60]	train-mlogloss:0.56647	eval-mlogloss:0.53654
[61]	train-mlogloss:0.56146	eval-mlogloss:0.53125
[62]	train-mlogloss:0.55585	eval-mlogloss:0.52503
[63]	train-mlogloss:0.55055	eval-mlogloss:0.51901
[64]	train-mlogloss:0.54541	eval-mlogloss:0.51372
[65]	train-mlogloss:0.54046	eval-mlogloss:0.50851
[66]	train-mlogloss:0.53545	eval-mlogloss:0.50297
[67]	train-mlogloss:0.53030	eval-mlogloss:0.49748
[68]	train-mlogloss:0.52526	eval-mlogloss:0.49231
[69]	train-mlogloss:0.52045	eval-mlogloss:0.48708
[70]	train-mlogloss:0.51576	eval-mlogloss:0.48201
[71]	train-mlogloss:0.51122	eval-mlogloss:0.47718
[72]	train-mlogloss:0.50630	eval-mlogloss:0.47217
[73]	train-mlogloss:0.50210	eval-mlogloss:0.46710
[74]	train-mlogloss:0.49826	eval-mlogloss:0.46309
[75]	train-mlogloss:0.49356	eval-mlogloss:0.45788
[76]	train-mlogloss:0.48891	eval-mlogloss:0.45284
[77]	train-mlogloss:0.48454	eval-mlogloss:0.44829
[78]	train-mlogloss:0.48064	eval-mlogloss:0.44452
[79]	train-mlogloss:0.47614	eval-mlogloss:0.43958
[80]	train-mlogloss:0.47197	eval-mlogloss:0.43516
[81]	train-mlogloss:0.46808	eval-mlogloss:0.43119
[82]	train-mlogloss:0.46383	eval-mlogloss:0.42661
[83]	train-mlogloss:0.45992	eval-mlogloss:0.42215
[84]	train-mlogloss:0.45616	eval-mlogloss:0.41824
[85]	train-mlogloss:0.45206	eval-mlogloss:0.41380
[86]	train-mlogloss:0.44824	eval-mlogloss:0.40972
[87]	train-mlogloss:0.44442	eval-mlogloss:0.40564
[88]	train-mlogloss:0.44054	eval-mlogloss:0.40138
[89]	train-mlogloss:0.43691	eval-mlogloss:0.39757
[90]	train-mlogloss:0.43307	eval-mlogloss:0.39361
[91]	train-mlogloss:0.42918	eval-mlogloss:0.38942
[92]	train-mlogloss:0.42600	eval-mlogloss:0.38588
[93]	train-mlogloss:0.42237	eval-mlogloss:0.38200
[94]	train-mlogloss:0.41887	eval-mlogloss:0.37807
[95]	train-mlogloss:0.41549	eval-mlogloss:0.37426
[96]	train-mlogloss:0.41206	eval-mlogloss:0.37055
[97]	train-mlogloss:0.40880	eval-mlogloss:0.36729
[98]	train-mlogloss:0.40563	eval-mlogloss:0.36385
[99]	train-mlogloss:0.40242	eval-mlogloss:0.36035
[100]	train-mlogloss:0.39929	eval-mlogloss:0.35691
[101]	train-mlogloss:0.39597	eval-mlogloss:0.35324
[102]	train-mlogloss:0.39291	eval-mlogloss:0.34975
[103]	train-mlogloss:0.39000	eval-mlogloss:0.34641
[104]	train-mlogloss:0.38697	eval-mlogloss:0.34308
[105]	train-mlogloss:0.38428	eval-mlogloss:0.34043
[106]	train-mlogloss:0.38110	eval-mlogloss:0.33695
[107]	train-mlogloss:0.37831	eval-mlogloss:0.33365
[108]	train-mlogloss:0.37517	eval-mlogloss:0.33036
[109]	train-mlogloss:0.37246	eval-mlogloss:0.32729
[110]	train-mlogloss:0.36990	eval-mlogloss:0.32473
[111]	train-mlogloss:0.36756	eval-mlogloss:0.32214
[112]	train-mlogloss:0.36470	eval-mlogloss:0.31909
[113]	train-mlogloss:0.36243	eval-mlogloss:0.31642
[114]	train-mlogloss:0.35990	eval-mlogloss:0.31353
[115]	train-mlogloss:0.35701	eval-mlogloss:0.31037
[116]	train-mlogloss:0.35441	eval-mlogloss:0.30759
[117]	train-mlogloss:0.35208	eval-mlogloss:0.30505
[118]	train-mlogloss:0.34976	eval-mlogloss:0.30243
[119]	train-mlogloss:0.34726	eval-mlogloss:0.29979
[120]	train-mlogloss:0.34464	eval-mlogloss:0.29696
[121]	train-mlogloss:0.34270	eval-mlogloss:0.29496
[122]	train-mlogloss:0.34059	eval-mlogloss:0.29252
[123]	train-mlogloss:0.33878	eval-mlogloss:0.29057
[124]	train-mlogloss:0.33680	eval-mlogloss:0.28831
[125]	train-mlogloss:0.33471	eval-mlogloss:0.28628
[126]	train-mlogloss:0.33239	eval-mlogloss:0.28371
[127]	train-mlogloss:0.33041	eval-mlogloss:0.28178

[I 2026-06-28 16:06:30,762] Trial 31 pruned. Trial was pruned at iteration 128.

[0]	train-mlogloss:1.07026	eval-mlogloss:1.07138
[1]	train-mlogloss:1.04140	eval-mlogloss:1.04188
[2]	train-mlogloss:1.01478	eval-mlogloss:1.01374
[3]	train-mlogloss:0.98940	eval-mlogloss:0.98532
[4]	train-mlogloss:0.96351	eval-mlogloss:0.95829
[5]	train-mlogloss:0.93851	eval-mlogloss:0.93163
[6]	train-mlogloss:0.91631	eval-mlogloss:0.90749
[7]	train-mlogloss:0.89327	eval-mlogloss:0.88212

[I 2026-06-28 16:06:30,787] Trial 32 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.03428	eval-mlogloss:1.03426
[1]	train-mlogloss:0.97468	eval-mlogloss:0.97358

[I 2026-06-28 16:06:30,803] Trial 33 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.78786	eval-mlogloss:0.78164
[1]	train-mlogloss:0.58920	eval-mlogloss:0.57673

[I 2026-06-28 16:06:30,819] Trial 34 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.98824	eval-mlogloss:0.98218
[1]	train-mlogloss:0.89475	eval-mlogloss:0.88707

[I 2026-06-28 16:06:30,835] Trial 35 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.08508	eval-mlogloss:1.08711
[1]	train-mlogloss:1.07143	eval-mlogloss:1.07320
[2]	train-mlogloss:1.05777	eval-mlogloss:1.05869
[3]	train-mlogloss:1.04492	eval-mlogloss:1.04513
[4]	train-mlogloss:1.03196	eval-mlogloss:1.03177
[5]	train-mlogloss:1.01905	eval-mlogloss:1.01750
[6]	train-mlogloss:1.00920	eval-mlogloss:1.00742
[7]	train-mlogloss:1.00097	eval-mlogloss:0.99870
[8]	train-mlogloss:0.98860	eval-mlogloss:0.98576
[9]	train-mlogloss:0.97644	eval-mlogloss:0.97326
[10]	train-mlogloss:0.96788	eval-mlogloss:0.96449
[11]	train-mlogloss:0.95623	eval-mlogloss:0.95204
[12]	train-mlogloss:0.94737	eval-mlogloss:0.94271
[13]	train-mlogloss:0.93996	eval-mlogloss:0.93541
[14]	train-mlogloss:0.93076	eval-mlogloss:0.92557
[15]	train-mlogloss:0.92052	eval-mlogloss:0.91452
[16]	train-mlogloss:0.91197	eval-mlogloss:0.90600
[17]	train-mlogloss:0.90147	eval-mlogloss:0.89490
[18]	train-mlogloss:0.89325	eval-mlogloss:0.88676
[19]	train-mlogloss:0.88296	eval-mlogloss:0.87531
[20]	train-mlogloss:0.87498	eval-mlogloss:0.86690
[21]	train-mlogloss:0.86506	eval-mlogloss:0.85618
[22]	train-mlogloss:0.85745	eval-mlogloss:0.84788
[23]	train-mlogloss:0.84801	eval-mlogloss:0.83813
[24]	train-mlogloss:0.83870	eval-mlogloss:0.82854
[25]	train-mlogloss:0.82921	eval-mlogloss:0.81872
[26]	train-mlogloss:0.81965	eval-mlogloss:0.80827
[27]	train-mlogloss:0.80992	eval-mlogloss:0.79798
[28]	train-mlogloss:0.80145	eval-mlogloss:0.78859
[29]	train-mlogloss:0.79282	eval-mlogloss:0.77935
[30]	train-mlogloss:0.78451	eval-mlogloss:0.77040
[31]	train-mlogloss:0.77598	eval-mlogloss:0.76103
[32]	train-mlogloss:0.76766	eval-mlogloss:0.75224
[33]	train-mlogloss:0.75892	eval-mlogloss:0.74297
[34]	train-mlogloss:0.75069	eval-mlogloss:0.73397
[35]	train-mlogloss:0.74268	eval-mlogloss:0.72517
[36]	train-mlogloss:0.73537	eval-mlogloss:0.71769
[37]	train-mlogloss:0.72913	eval-mlogloss:0.71126
[38]	train-mlogloss:0.72211	eval-mlogloss:0.70375
[39]	train-mlogloss:0.71557	eval-mlogloss:0.69668
[40]	train-mlogloss:0.70868	eval-mlogloss:0.68910
[41]	train-mlogloss:0.70136	eval-mlogloss:0.68122
[42]	train-mlogloss:0.69398	eval-mlogloss:0.67328
[43]	train-mlogloss:0.68873	eval-mlogloss:0.66814
[44]	train-mlogloss:0.68323	eval-mlogloss:0.66241
[45]	train-mlogloss:0.67868	eval-mlogloss:0.65746
[46]	train-mlogloss:0.67115	eval-mlogloss:0.64913
[47]	train-mlogloss:0.66436	eval-mlogloss:0.64208
[48]	train-mlogloss:0.65841	eval-mlogloss:0.63643
[49]	train-mlogloss:0.65175	eval-mlogloss:0.62900
[50]	train-mlogloss:0.64604	eval-mlogloss:0.62318
[51]	train-mlogloss:0.64155	eval-mlogloss:0.61837
[52]	train-mlogloss:0.63503	eval-mlogloss:0.61147
[53]	train-mlogloss:0.62937	eval-mlogloss:0.60548
[54]	train-mlogloss:0.62441	eval-mlogloss:0.60037
[55]	train-mlogloss:0.61815	eval-mlogloss:0.59336
[56]	train-mlogloss:0.61315	eval-mlogloss:0.58836
[57]	train-mlogloss:0.60763	eval-mlogloss:0.58256
[58]	train-mlogloss:0.60166	eval-mlogloss:0.57619
[59]	train-mlogloss:0.59642	eval-mlogloss:0.57014
[60]	train-mlogloss:0.59117	eval-mlogloss:0.56421
[61]	train-mlogloss:0.58616	eval-mlogloss:0.55884
[62]	train-mlogloss:0.58174	eval-mlogloss:0.55362
[63]	train-mlogloss:0.57747	eval-mlogloss:0.54923
[64]	train-mlogloss:0.57195	eval-mlogloss:0.54348
[65]	train-mlogloss:0.56857	eval-mlogloss:0.53976
[66]	train-mlogloss:0.56385	eval-mlogloss:0.53467
[67]	train-mlogloss:0.56090	eval-mlogloss:0.53162
[68]	train-mlogloss:0.55633	eval-mlogloss:0.52693
[69]	train-mlogloss:0.55264	eval-mlogloss:0.52243
[70]	train-mlogloss:0.54803	eval-mlogloss:0.51745
[71]	train-mlogloss:0.54491	eval-mlogloss:0.51402
[72]	train-mlogloss:0.54003	eval-mlogloss:0.50921
[73]	train-mlogloss:0.53667	eval-mlogloss:0.50535
[74]	train-mlogloss:0.53292	eval-mlogloss:0.50112
[75]	train-mlogloss:0.52981	eval-mlogloss:0.49761
[76]	train-mlogloss:0.52600	eval-mlogloss:0.49351
[77]	train-mlogloss:0.52308	eval-mlogloss:0.49048
[78]	train-mlogloss:0.51977	eval-mlogloss:0.48714
[79]	train-mlogloss:0.51583	eval-mlogloss:0.48288
[80]	train-mlogloss:0.51386	eval-mlogloss:0.48094
[81]	train-mlogloss:0.51048	eval-mlogloss:0.47731
[82]	train-mlogloss:0.50691	eval-mlogloss:0.47370
[83]	train-mlogloss:0.50332	eval-mlogloss:0.46994
[84]	train-mlogloss:0.50080	eval-mlogloss:0.46733
[85]	train-mlogloss:0.49828	eval-mlogloss:0.46464
[86]	train-mlogloss:0.49492	eval-mlogloss:0.46101
[87]	train-mlogloss:0.49127	eval-mlogloss:0.45678
[88]	train-mlogloss:0.48938	eval-mlogloss:0.45474
[89]	train-mlogloss:0.48545	eval-mlogloss:0.45044
[90]	train-mlogloss:0.48150	eval-mlogloss:0.44623
[91]	train-mlogloss:0.47911	eval-mlogloss:0.44341
[92]	train-mlogloss:0.47561	eval-mlogloss:0.43960
[93]	train-mlogloss:0.47261	eval-mlogloss:0.43607
[94]	train-mlogloss:0.46907	eval-mlogloss:0.43239
[95]	train-mlogloss:0.46593	eval-mlogloss:0.42877
[96]	train-mlogloss:0.46297	eval-mlogloss:0.42558
[97]	train-mlogloss:0.45938	eval-mlogloss:0.42157
[98]	train-mlogloss:0.45684	eval-mlogloss:0.41862
[99]	train-mlogloss:0.45406	eval-mlogloss:0.41560
[100]	train-mlogloss:0.45193	eval-mlogloss:0.41321
[101]	train-mlogloss:0.44807	eval-mlogloss:0.40874
[102]	train-mlogloss:0.44517	eval-mlogloss:0.40543
[103]	train-mlogloss:0.44229	eval-mlogloss:0.40215
[104]	train-mlogloss:0.43889	eval-mlogloss:0.39828
[105]	train-mlogloss:0.43602	eval-mlogloss:0.39523
[106]	train-mlogloss:0.43372	eval-mlogloss:0.39276
[107]	train-mlogloss:0.43099	eval-mlogloss:0.38957
[108]	train-mlogloss:0.42831	eval-mlogloss:0.38670
[109]	train-mlogloss:0.42593	eval-mlogloss:0.38420
[110]	train-mlogloss:0.42414	eval-mlogloss:0.38227
[111]	train-mlogloss:0.42204	eval-mlogloss:0.37973
[112]	train-mlogloss:0.41891	eval-mlogloss:0.37635
[113]	train-mlogloss:0.41662	eval-mlogloss:0.37374
[114]	train-mlogloss:0.41468	eval-mlogloss:0.37161
[115]	train-mlogloss:0.41184	eval-mlogloss:0.36853
[116]	train-mlogloss:0.40937	eval-mlogloss:0.36605
[117]	train-mlogloss:0.40700	eval-mlogloss:0.36346
[118]	train-mlogloss:0.40466	eval-mlogloss:0.36100
[119]	train-mlogloss:0.40217	eval-mlogloss:0.35813
[120]	train-mlogloss:0.39995	eval-mlogloss:0.35574
[121]	train-mlogloss:0.39856	eval-mlogloss:0.35424
[122]	train-mlogloss:0.39680	eval-mlogloss:0.35232
[123]	train-mlogloss:0.39500	eval-mlogloss:0.35054
[124]	train-mlogloss:0.39273	eval-mlogloss:0.34815
[125]	train-mlogloss:0.39074	eval-mlogloss:0.34601
[126]	train-mlogloss:0.38824	eval-mlogloss:0.34320
[127]	train-mlogloss:0.38632	eval-mlogloss:0.34117
[128]	train-mlogloss:0.38424	eval-mlogloss:0.33888
[129]	train-mlogloss:0.38313	eval-mlogloss:0.33752
[130]	train-mlogloss:0.38095	eval-mlogloss:0.33520
[131]	train-mlogloss:0.37925	eval-mlogloss:0.33308
[132]	train-mlogloss:0.37663	eval-mlogloss:0.33006
[133]	train-mlogloss:0.37450	eval-mlogloss:0.32809
[134]	train-mlogloss:0.37259	eval-mlogloss:0.32602
[135]	train-mlogloss:0.37066	eval-mlogloss:0.32398
[136]	train-mlogloss:0.36886	eval-mlogloss:0.32176
[137]	train-mlogloss:0.36701	eval-mlogloss:0.31977
[138]	train-mlogloss:0.36511	eval-mlogloss:0.31773
[139]	train-mlogloss:0.36317	eval-mlogloss:0.31569
[140]	train-mlogloss:0.36164	eval-mlogloss:0.31381
[141]	train-mlogloss:0.36070	eval-mlogloss:0.31270
[142]	train-mlogloss:0.35912	eval-mlogloss:0.31103
[143]	train-mlogloss:0.35741	eval-mlogloss:0.30922
[144]	train-mlogloss:0.35637	eval-mlogloss:0.30805
[145]	train-mlogloss:0.35467	eval-mlogloss:0.30612
[146]	train-mlogloss:0.35272	eval-mlogloss:0.30387
[147]	train-mlogloss:0.35141	eval-mlogloss:0.30230
[148]	train-mlogloss:0.34976	eval-mlogloss:0.30062
[149]	train-mlogloss:0.34937	eval-mlogloss:0.30011
[150]	train-mlogloss:0.34913	eval-mlogloss:0.29979
[151]	train-mlogloss:0.34744	eval-mlogloss:0.29804
[152]	train-mlogloss:0.34674	eval-mlogloss:0.29722
[153]	train-mlogloss:0.34546	eval-mlogloss:0.29568
[154]	train-mlogloss:0.34441	eval-mlogloss:0.29452
[155]	train-mlogloss:0.34266	eval-mlogloss:0.29257
[156]	train-mlogloss:0.34182	eval-mlogloss:0.29143
[157]	train-mlogloss:0.33992	eval-mlogloss:0.28943
[158]	train-mlogloss:0.33920	eval-mlogloss:0.28863
[159]	train-mlogloss:0.33831	eval-mlogloss:0.28732
[160]	train-mlogloss:0.33823	eval-mlogloss:0.28712
[161]	train-mlogloss:0.33635	eval-mlogloss:0.28496
[162]	train-mlogloss:0.33477	eval-mlogloss:0.28318
[163]	train-mlogloss:0.33395	eval-mlogloss:0.28226
[164]	train-mlogloss:0.33232	eval-mlogloss:0.28054
[165]	train-mlogloss:0.33066	eval-mlogloss:0.27851
[166]	train-mlogloss:0.33034	eval-mlogloss:0.27811
[167]	train-mlogloss:0.32957	eval-mlogloss:0.27730
[168]	train-mlogloss:0.32885	eval-mlogloss:0.27663
[169]	train-mlogloss:0.32874	eval-mlogloss:0.27634
[170]	train-mlogloss:0.32729	eval-mlogloss:0.27480
[171]	train-mlogloss:0.32654	eval-mlogloss:0.27390
[172]	train-mlogloss:0.32578	eval-mlogloss:0.27283
[173]	train-mlogloss:0.32500	eval-mlogloss:0.27189
[174]	train-mlogloss:0.32428	eval-mlogloss:0.27108
[175]	train-mlogloss:0.32356	eval-mlogloss:0.27011
[176]	train-mlogloss:0.32344	eval-mlogloss:0.26997
[177]	train-mlogloss:0.32164	eval-mlogloss:0.26800
[178]	train-mlogloss:0.32098	eval-mlogloss:0.26723
[179]	train-mlogloss:0.32040	eval-mlogloss:0.26643
[180]	train-mlogloss:0.31980	eval-mlogloss:0.26571
[181]	train-mlogloss:0.31981	eval-mlogloss:0.26569
[182]	train-mlogloss:0.31812	eval-mlogloss:0.26375
[183]	train-mlogloss:0.31668	eval-mlogloss:0.26225
[184]	train-mlogloss:0.31608	eval-mlogloss:0.26148
[185]	train-mlogloss:0.31520	eval-mlogloss:0.26064
[186]	train-mlogloss:0.31514	eval-mlogloss:0.26063
[187]	train-mlogloss:0.31447	eval-mlogloss:0.25986
[188]	train-mlogloss:0.31377	eval-mlogloss:0.25896
[189]	train-mlogloss:0.31284	eval-mlogloss:0.25789
[190]	train-mlogloss:0.31276	eval-mlogloss:0.25777
[191]	train-mlogloss:0.31261	eval-mlogloss:0.25754
[192]	train-mlogloss:0.31197	eval-mlogloss:0.25678
[193]	train-mlogloss:0.31133	eval-mlogloss:0.25605
[194]	train-mlogloss:0.31107	eval-mlogloss:0.25572
[195]	train-mlogloss:0.31106	eval-mlogloss:0.25572
[196]	train-mlogloss:0.31022	eval-mlogloss:0.25475
[197]	train-mlogloss:0.30960	eval-mlogloss:0.25408
[198]	train-mlogloss:0.30942	eval-mlogloss:0.25381
[199]	train-mlogloss:0.30805	eval-mlogloss:0.25239
[200]	train-mlogloss:0.30756	eval-mlogloss:0.25182
[201]	train-mlogloss:0.30708	eval-mlogloss:0.25121
[202]	train-mlogloss:0.30657	eval-mlogloss:0.25079
[203]	train-mlogloss:0.30650	eval-mlogloss:0.25076
[204]	train-mlogloss:0.30590	eval-mlogloss:0.25013
[205]	train-mlogloss:0.30513	eval-mlogloss:0.24903
[206]	train-mlogloss:0.30508	eval-mlogloss:0.24888
[207]	train-mlogloss:0.30496	eval-mlogloss:0.24872
[208]	train-mlogloss:0.30485	eval-mlogloss:0.24867
[209]	train-mlogloss:0.30464	eval-mlogloss:0.24826
[210]	train-mlogloss:0.30460	eval-mlogloss:0.24824
[211]	train-mlogloss:0.30397	eval-mlogloss:0.24752
[212]	train-mlogloss:0.30378	eval-mlogloss:0.24732
[213]	train-mlogloss:0.30330	eval-mlogloss:0.24668
[214]	train-mlogloss:0.30321	eval-mlogloss:0.24656
[215]	train-mlogloss:0.30274	eval-mlogloss:0.24600
[216]	train-mlogloss:0.30267	eval-mlogloss:0.24595
[217]	train-mlogloss:0.30267	eval-mlogloss:0.24594
[218]	train-mlogloss:0.30260	eval-mlogloss:0.24575
[219]	train-mlogloss:0.30193	eval-mlogloss:0.24497
[220]	train-mlogloss:0.30193	eval-mlogloss:0.24496
[221]	train-mlogloss:0.30134	eval-mlogloss:0.24434
[222]	train-mlogloss:0.30074	eval-mlogloss:0.24374
[223]	train-mlogloss:0.29973	eval-mlogloss:0.24269
[224]	train-mlogloss:0.29920	eval-mlogloss:0.24209
[225]	train-mlogloss:0.29920	eval-mlogloss:0.24208
[226]	train-mlogloss:0.29884	eval-mlogloss:0.24169
[227]	train-mlogloss:0.29871	eval-mlogloss:0.24153
[228]	train-mlogloss:0.29823	eval-mlogloss:0.24095
[229]	train-mlogloss:0.29801	eval-mlogloss:0.24053
[230]	train-mlogloss:0.29788	eval-mlogloss:0.24032
[231]	train-mlogloss:0.29775	eval-mlogloss:0.24018
[232]	train-mlogloss:0.29720	eval-mlogloss:0.23949
[233]	train-mlogloss:0.29711	eval-mlogloss:0.23945
[234]	train-mlogloss:0.29711	eval-mlogloss:0.23946
[235]	train-mlogloss:0.29658	eval-mlogloss:0.23875
[236]	train-mlogloss:0.29607	eval-mlogloss:0.23794
[237]	train-mlogloss:0.29599	eval-mlogloss:0.23787
[238]	train-mlogloss:0.29523	eval-mlogloss:0.23695
[239]	train-mlogloss:0.29523	eval-mlogloss:0.23694
[240]	train-mlogloss:0.29523	eval-mlogloss:0.23693
[241]	train-mlogloss:0.29464	eval-mlogloss:0.23614
[242]	train-mlogloss:0.29464	eval-mlogloss:0.23614
[243]	train-mlogloss:0.29422	eval-mlogloss:0.23555
[244]	train-mlogloss:0.29414	eval-mlogloss:0.23551
[245]	train-mlogloss:0.29405	eval-mlogloss:0.23529
[246]	train-mlogloss:0.29405	eval-mlogloss:0.23531
[247]	train-mlogloss:0.29354	eval-mlogloss:0.23469
[248]	train-mlogloss:0.29348	eval-mlogloss:0.23448
[249]	train-mlogloss:0.29346	eval-mlogloss:0.23452
[250]	train-mlogloss:0.29340	eval-mlogloss:0.23444
[251]	train-mlogloss:0.29334	eval-mlogloss:0.23442
[252]	train-mlogloss:0.29321	eval-mlogloss:0.23419
[253]	train-mlogloss:0.29257	eval-mlogloss:0.23334
[254]	train-mlogloss:0.29253	eval-mlogloss:0.23330
[255]	train-mlogloss:0.29178	eval-mlogloss:0.23255
[256]	train-mlogloss:0.29178	eval-mlogloss:0.23256
[257]	train-mlogloss:0.29174	eval-mlogloss:0.23251
[258]	train-mlogloss:0.29168	eval-mlogloss:0.23249
[259]	train-mlogloss:0.29163	eval-mlogloss:0.23247
[260]	train-mlogloss:0.29160	eval-mlogloss:0.23245
[261]	train-mlogloss:0.29154	eval-mlogloss:0.23237
[262]	train-mlogloss:0.29149	eval-mlogloss:0.23224
[263]	train-mlogloss:0.29143	eval-mlogloss:0.23220
[264]	train-mlogloss:0.29101	eval-mlogloss:0.23172
[265]	train-mlogloss:0.29064	eval-mlogloss:0.23129
[266]	train-mlogloss:0.29026	eval-mlogloss:0.23083
[267]	train-mlogloss:0.29025	eval-mlogloss:0.23084
[268]	train-mlogloss:0.29006	eval-mlogloss:0.23068
[269]	train-mlogloss:0.29002	eval-mlogloss:0.23066
[270]	train-mlogloss:0.28941	eval-mlogloss:0.22978
[271]	train-mlogloss:0.28940	eval-mlogloss:0.22979
[272]	train-mlogloss:0.28932	eval-mlogloss:0.22951
[273]	train-mlogloss:0.28924	eval-mlogloss:0.22942
[274]	train-mlogloss:0.28924	eval-mlogloss:0.22942
[275]	train-mlogloss:0.28832	eval-mlogloss:0.22838
[276]	train-mlogloss:0.28832	eval-mlogloss:0.22837
[277]	train-mlogloss:0.28832	eval-mlogloss:0.22837
[278]	train-mlogloss:0.28778	eval-mlogloss:0.22770
[279]	train-mlogloss:0.28778	eval-mlogloss:0.22771
[280]	train-mlogloss:0.28777	eval-mlogloss:0.22772
[281]	train-mlogloss:0.28777	eval-mlogloss:0.22773
[282]	train-mlogloss:0.28777	eval-mlogloss:0.22771
[283]	train-mlogloss:0.28735	eval-mlogloss:0.22720
[284]	train-mlogloss:0.28656	eval-mlogloss:0.22648
[285]	train-mlogloss:0.28656	eval-mlogloss:0.22648
[286]	train-mlogloss:0.28656	eval-mlogloss:0.22649
[287]	train-mlogloss:0.28656	eval-mlogloss:0.22650
[288]	train-mlogloss:0.28656	eval-mlogloss:0.22650
[289]	train-mlogloss:0.28604	eval-mlogloss:0.22582
[290]	train-mlogloss:0.28603	eval-mlogloss:0.22582
[291]	train-mlogloss:0.28603	eval-mlogloss:0.22582
[292]	train-mlogloss:0.28551	eval-mlogloss:0.22498
[293]	train-mlogloss:0.28551	eval-mlogloss:0.22497
[294]	train-mlogloss:0.28551	eval-mlogloss:0.22497
[295]	train-mlogloss:0.28547	eval-mlogloss:0.22495
[296]	train-mlogloss:0.28541	eval-mlogloss:0.22491
[297]	train-mlogloss:0.28536	eval-mlogloss:0.22489
[298]	train-mlogloss:0.28536	eval-mlogloss:0.22490
[299]	train-mlogloss:0.28528	eval-mlogloss:0.22487

[I 2026-06-28 16:06:31,264] Trial 36 finished with value: 1.0 and parameters: {'lambda': 5.3572534191071214e-05, 'alpha': 8.753131291702972e-05, 'eta': 0.010826155639590072, 'gamma': 0.28321399733814384, 'max_depth': 6, 'min_child_weight': 8, 'subsample': 0.5730798680765022, 'colsample_bytree': 0.5218297451849694}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:1.05491	eval-mlogloss:1.05640
[1]	train-mlogloss:1.01526	eval-mlogloss:1.01458
[2]	train-mlogloss:0.98346	eval-mlogloss:0.98068
[3]	train-mlogloss:0.95065	eval-mlogloss:0.94641
[4]	train-mlogloss:0.91839	eval-mlogloss:0.91204
[5]	train-mlogloss:0.88314	eval-mlogloss:0.87432
[6]	train-mlogloss:0.85719	eval-mlogloss:0.84764
[7]	train-mlogloss:0.83739	eval-mlogloss:0.82466

[I 2026-06-28 16:06:31,287] Trial 37 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:0.99578	eval-mlogloss:0.98887
[1]	train-mlogloss:0.90745	eval-mlogloss:0.89901

[I 2026-06-28 16:06:31,301] Trial 38 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.97081	eval-mlogloss:0.96509
[1]	train-mlogloss:0.86264	eval-mlogloss:0.85479

[I 2026-06-28 16:06:31,317] Trial 39 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.06608	eval-mlogloss:1.06659
[1]	train-mlogloss:1.03299	eval-mlogloss:1.03257
[2]	train-mlogloss:1.00155	eval-mlogloss:0.99901
[3]	train-mlogloss:0.97239	eval-mlogloss:0.96886
[4]	train-mlogloss:0.94375	eval-mlogloss:0.93861
[5]	train-mlogloss:0.91637	eval-mlogloss:0.90997
[6]	train-mlogloss:0.89135	eval-mlogloss:0.88232
[7]	train-mlogloss:0.86602	eval-mlogloss:0.85559

[I 2026-06-28 16:06:31,342] Trial 40 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.07578	eval-mlogloss:1.07726
[1]	train-mlogloss:1.05430	eval-mlogloss:1.05486
[2]	train-mlogloss:1.03267	eval-mlogloss:1.03191
[3]	train-mlogloss:1.01207	eval-mlogloss:1.00901
[4]	train-mlogloss:0.99110	eval-mlogloss:0.98735
[5]	train-mlogloss:0.97041	eval-mlogloss:0.96526
[6]	train-mlogloss:0.95136	eval-mlogloss:0.94412
[7]	train-mlogloss:0.93183	eval-mlogloss:0.92286

[I 2026-06-28 16:06:31,369] Trial 41 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.05466	eval-mlogloss:1.05523
[1]	train-mlogloss:1.01262	eval-mlogloss:1.01251

[I 2026-06-28 16:06:31,385] Trial 42 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.02526	eval-mlogloss:1.02492
[1]	train-mlogloss:0.95821	eval-mlogloss:0.95664

[I 2026-06-28 16:06:31,401] Trial 43 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.08420	eval-mlogloss:1.08601
[1]	train-mlogloss:1.06981	eval-mlogloss:1.07084
[2]	train-mlogloss:1.05525	eval-mlogloss:1.05574
[3]	train-mlogloss:1.04429	eval-mlogloss:1.04440
[4]	train-mlogloss:1.03061	eval-mlogloss:1.03004
[5]	train-mlogloss:1.01691	eval-mlogloss:1.01518
[6]	train-mlogloss:1.00610	eval-mlogloss:1.00426
[7]	train-mlogloss:0.99478	eval-mlogloss:0.99233
[8]	train-mlogloss:0.98191	eval-mlogloss:0.97919
[9]	train-mlogloss:0.96904	eval-mlogloss:0.96593
[10]	train-mlogloss:0.96011	eval-mlogloss:0.95654
[11]	train-mlogloss:0.94760	eval-mlogloss:0.94318
[12]	train-mlogloss:0.93512	eval-mlogloss:0.93009
[13]	train-mlogloss:0.92395	eval-mlogloss:0.91874
[14]	train-mlogloss:0.91192	eval-mlogloss:0.90641
[15]	train-mlogloss:0.90097	eval-mlogloss:0.89501
[16]	train-mlogloss:0.88954	eval-mlogloss:0.88263
[17]	train-mlogloss:0.87842	eval-mlogloss:0.87101
[18]	train-mlogloss:0.86900	eval-mlogloss:0.86166
[19]	train-mlogloss:0.86133	eval-mlogloss:0.85348
[20]	train-mlogloss:0.85061	eval-mlogloss:0.84191
[21]	train-mlogloss:0.84023	eval-mlogloss:0.83073
[22]	train-mlogloss:0.83247	eval-mlogloss:0.82158
[23]	train-mlogloss:0.82303	eval-mlogloss:0.81173
[24]	train-mlogloss:0.81409	eval-mlogloss:0.80205
[25]	train-mlogloss:0.80527	eval-mlogloss:0.79269
[26]	train-mlogloss:0.79515	eval-mlogloss:0.78162
[27]	train-mlogloss:0.78519	eval-mlogloss:0.77133
[28]	train-mlogloss:0.77633	eval-mlogloss:0.76139
[29]	train-mlogloss:0.76779	eval-mlogloss:0.75209
[30]	train-mlogloss:0.75939	eval-mlogloss:0.74284
[31]	train-mlogloss:0.75106	eval-mlogloss:0.73433

[I 2026-06-28 16:06:31,467] Trial 44 pruned. Trial was pruned at iteration 32.

[0]	train-mlogloss:1.04762	eval-mlogloss:1.04715
[1]	train-mlogloss:0.99869	eval-mlogloss:0.99741

[I 2026-06-28 16:06:31,486] Trial 45 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.97115	eval-mlogloss:0.96975
[1]	train-mlogloss:0.86421	eval-mlogloss:0.85925

[I 2026-06-28 16:06:31,505] Trial 46 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.02146	eval-mlogloss:1.02266
[1]	train-mlogloss:0.93926	eval-mlogloss:0.93841

[I 2026-06-28 16:06:31,523] Trial 47 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.06952	eval-mlogloss:1.07015
[1]	train-mlogloss:1.04061	eval-mlogloss:1.04073
[2]	train-mlogloss:1.01229	eval-mlogloss:1.01019
[3]	train-mlogloss:0.98574	eval-mlogloss:0.98162
[4]	train-mlogloss:0.95966	eval-mlogloss:0.95406
[5]	train-mlogloss:0.93448	eval-mlogloss:0.92820
[6]	train-mlogloss:0.91124	eval-mlogloss:0.90233
[7]	train-mlogloss:0.88812	eval-mlogloss:0.87776

[I 2026-06-28 16:06:31,551] Trial 48 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.05610	eval-mlogloss:1.05258
[1]	train-mlogloss:1.01812	eval-mlogloss:1.01557

[I 2026-06-28 16:06:31,568] Trial 49 pruned. Trial was pruned at iteration 2.

Best trial: {'lambda': 0.06003346775403882, 'alpha': 4.744688065878044e-06, 'eta': 0.08908659228768515, 'gamma': 2.2743632008920925e-05, 'max_depth': 6, 'min_child_weight': 10, 'subsample': 0.7322566045414369, 'colsample_bytree': 0.4361896547662477}
Best accuracy: 1.0

In [37]:
from optuna.visualization import plot_intermediate_values

# 1. Plot intermediate values during the trials
plot_intermediate_values(study).show()